Class {
	#name : #AOC2020Tests,
	#superclass : #TestCase,
	#category : #'AdventOfCode2020-Tests'
}

{ #category : #data }
AOC2020Tests >> dataForDay01 [
^ #(
1935
1956
1991
1425
1671
1537
1984
1569
1873
1840
1720
1937
1823
1625
1727
1812
1714
1900
1939
1931
1951
1756
1942
1611
1979
1930
1996
2000
1544
1780
1687
1760
1836
1814
1691
1817
1964
1899
1577
1547
866
1560
1988
1601
1970
1738
1507
1667
1851
1933
1515
1856
1969
1860
1801
2007
1866
1800
1749
1843
1711
1495
1905
763
1672
1858
1987
1492
1849
1993
1737
1874
1658
1810
1665
1768
1950
1879
1816
1868
1995
1763
1783
1833
1968
1847
1748
1725
1891
1755
286
1976
1977
1655
1808
1986
1779
1861
1953
1888
1792
1811
1872
1790
1839
1985
1827
1842
1925
1735
1635
1821
1820
1973
1531
1770
59
1846
1932
1907
1730
933
1395
1753
1751
361
1530
1782
1087
1589
1929
1795
1815
1732
1765
1877
1722
526
1709
1789
1892
1913
1662
1809
1670
1947
1835
1587
1758
1982
2009
1757
670
1983
1524
1878
1796
1952
566
1922
1882
1870
1799
1731
1724
1805
2003
1596
1566
1853
1911
1857
1739
1744
1627
1729
1745
1845
1582
1884
1883
1941
1764
1685
1791
1837
1697
1742
1781
1948
1876
1989
1643
1871
1906
1726
1958
1502
1927
1946
)
]

{ #category : #data }
AOC2020Tests >> dataForDay02 [
^
'9-12 q: qqqxhnhdmqqqqjz
12-16 z: zzzzzznwlzzjzdzf
4-7 s: sssgssw
13-14 p: pppqzpppppppfpppp
2-9 m: jknmmmmmmdmmmrm
4-5 b: bbbrb
2-10 c: hcpzpjclzc
7-11 f: ffpffffgfrff
4-5 j: qrrhjt
13-14 m: wfwvfxmchplldvm
8-9 l: lllllllll
5-9 v: knvvwptdvmchnkd
1-7 s: sssssqsss
6-14 j: jjjjjbjjjjjjjp
6-8 c: cccccqzf
9-18 h: hhhhchhdhghhhhhhhhch
2-3 s: bssswhs
3-4 c: bhtg
10-13 b: bbbbbbbbbbbbmb
15-16 l: lllllllmlllllllll
3-4 m: dwmmcmn
2-5 h: vqnbh
10-13 n: nnnnnnnnnnnnln
12-13 g: vxgggggggggggggg
4-5 h: hfhxlhh
6-16 k: xztrkkzkkkkhpksg
7-12 f: fpcffnfffdfwf
2-4 h: hwhk
7-8 p: pkpdppsgkt
2-4 r: rgvp
10-11 w: wwwwwwwwwwn
1-14 w: wwwwqwwwwwznwtzm
1-2 j: jjnjrsjjhjnv
19-20 c: cccccccccccccccccctt
1-7 h: hrhwhhxfh
2-3 p: whgpp
4-9 l: jqllllsllf
9-15 f: zffffffrtffffrpzxf
8-9 t: tdtttttgtt
19-20 l: sxspchxnngfcflghrmkl
8-10 c: xjxcccccbc
14-17 g: gggggggggggggmggp
17-19 w: wwwwwwwwwwwhwlwwgwv
2-4 v: vjvv
1-10 d: dffqltgzzdjdmhlddlfd
12-19 v: vzlvjvqvvlvvvwcrdvk
6-11 t: tttftttttttttg
5-9 g: dggwngggrg
2-9 w: ptbhsgwnrt
2-12 t: stjpthvlcnxt
4-6 d: wrhdbdddpdcd
8-10 n: wxnnnnnnncpnd
8-9 w: njdxwzdxw
11-17 q: rcjrfcqqxdkgqfqgf
7-11 t: tjvgkgttlstlstvrn
2-9 z: zjvbcdszczzp
5-13 g: kkhxgrqngnwjgfdvd
1-5 f: fffff
5-8 t: tttktttttt
6-7 p: tgksxzb
5-6 c: qcgccc
4-8 x: hghpslxx
2-7 t: tvrwtmb
7-15 p: zpnqpjpzpgcpppppqrtp
10-18 z: zzzzzzzzzzzzzzzzzb
5-10 t: kdmmtrckrtnhtvcfng
5-10 f: fzffffwfpfwftgflwp
12-16 c: fqkzccmnzhncbpch
2-11 t: ttdtctzttwttgktmt
10-11 l: mlplhlntmlkllllllhl
2-3 j: jjjqtcdc
2-3 b: kbcb
13-14 q: qlqzqqbcqhqqqq
12-14 b: bbbbbdkbbbbmbxbbn
8-18 p: wpzprzkkptvtpppnftp
6-12 k: fgkldkhkkcwkrck
5-6 j: srjjjjjjj
2-3 c: jhtc
3-4 q: qgdq
3-8 h: jphphhhh
5-6 w: wwwwvwn
5-10 r: jrrskrrgfgvtkrr
2-5 w: bmxlkkbtcdwc
2-7 t: ltlmxttdqsnh
17-20 z: zzzzzzzzzzzzzzjzzvzt
15-16 x: fxxxjxrrtdxdxxlz
4-8 q: fqtqzqkbq
15-16 w: wpzfvjnqpfrdlsgj
3-18 r: mprntrrzkfpkhxfzcg
19-20 j: jjrjjjjjjjjjjjjjjjph
3-5 s: ssfsw
3-17 h: nkczlnhhbmdqmklvw
2-7 x: slxkcxlqtwxjwjf
4-7 f: bwfgkffzfw
1-6 q: ssqqqnq
15-17 g: vjgpghvmcpghgxztl
11-14 f: sfffffbffgffffsffl
12-16 c: cccccccccmczccccc
15-18 w: wwwwwwwwwdwwwwwwwww
3-4 b: bkbb
4-8 t: ttrjmmsgbbtt
17-19 c: ccccccccccccccccwccc
10-12 x: xsxxxxxxtkxxxx
12-15 n: nlnnsnnnnnncpnm
6-9 h: hhhkhknxcrhhphzmtjr
2-4 m: mngs
1-6 n: cnnnbn
4-6 v: vvvxvm
5-13 w: qcftwjctgcvsbwgm
2-3 s: ssvss
15-16 f: vffqbhffffcfffrn
2-7 n: hnnhtnvpmxcqdnnf
3-4 t: tntct
8-9 k: qpkwkkzkk
9-11 z: pzznzzzzcsvc
2-5 h: mdhcpnhmnhk
3-6 r: cfgrhws
1-10 r: rrmrrrrrtr
10-12 w: wgkwwqwwwhnhwwzk
11-12 d: dvddddddddddd
3-8 j: jrhjjjjwswkjj
2-14 v: vpfghwfvkhwwjklklpl
4-5 z: jzmzzzz
4-6 g: dbtgggggtp
1-7 n: nkkwpkzjnddhpdnmtfj
6-12 b: bbbbbbbbbbbbbbwbbbb
4-6 z: zzqtzr
2-11 l: nzlrllznllsx
2-8 r: rrrrrrrr
14-16 n: vnnnnnnnnnnnnhnq
2-10 d: ddddddddddd
5-16 w: wlwwkwwwwmwwwwswwnd
8-12 d: ddddrjddddddddd
8-9 g: ggggggggg
9-14 w: wwwwzvmhxwfjwwwnw
3-5 d: ngrjkdpddjdl
1-3 r: trhr
3-5 j: tjgzj
6-13 b: bgjbbsbhbbfxrw
9-10 p: jpppppppdpp
4-5 p: ppppbpp
10-11 l: lllblllllkgll
16-17 z: rtdzlbcshlvcvvqzj
4-6 k: rdfknx
5-13 r: rrzrrrrrrrrrrrrrrr
7-9 b: dbbbbbbwb
1-8 h: jhhhhhhhhh
11-17 g: tqbghggghcgggglgdkg
4-7 v: bqvvvlvbcj
7-13 j: xjjjjdtjjjjlchjj
2-3 g: kbggglgqkkf
3-4 n: nnrn
2-4 c: mxcsz
7-18 q: pqqqcqzwxqfqqrqqqw
4-5 c: mckcc
3-6 z: wzdzznzz
14-17 w: bwwwwwwkwwwwwwwwfww
3-4 w: wwww
16-19 h: hhhhhhhlhhhhhhhtxkh
11-16 m: hmgcmtxxmpmdbdkm
2-6 w: twwwwdmwwww
4-5 h: phxnl
4-6 p: pppdpmgppppcv
13-14 d: xpdndklhdbbrdn
5-9 f: kfqfdfxrhftx
3-4 w: qfpx
7-9 d: ddddldddddddl
1-6 g: gggggg
3-5 h: hlgbnkc
3-4 p: ppvj
2-10 x: wgxlqfxtxx
2-5 n: nrgrn
10-11 g: bgggggggggg
3-4 p: pkprr
3-4 m: mmxrm
1-2 q: qqbpn
7-8 t: vcrzttjbtttjs
8-13 w: wwwwwwwwwhwwwwnwwwsw
2-8 g: ggggggghgg
6-7 g: gggghjg
4-5 q: qqgnwq
14-18 s: sssssssssssssfsssq
7-9 l: mgbsqgmlhmwv
6-9 q: qqbqqbrqq
2-4 m: nsktmqk
4-6 f: fffkfz
9-15 n: nvnjnnnvtnnhnnxn
7-9 v: vvqrvcdvvvnbv
4-6 g: mggggd
3-8 q: gqvzqqmq
8-10 r: rrrrrrrwrvr
1-10 v: vmkvpgvvxvxw
4-9 v: vmwfvxtlmgvtrndsv
6-7 f: fffffff
10-11 k: xkkkckkwkbsk
13-15 p: pppjhppjppfcpppppppp
2-9 r: mrlzlptrrv
4-7 k: bkshqnkkj
5-6 c: chcccxcjchkd
5-8 q: qdhqvqqsqqq
5-7 r: rrrrrrr
5-8 p: bfpqgpbgpqpp
3-5 v: vtvtvrqdj
1-2 g: gggg
3-4 b: pbbbbb
6-14 x: tdrjtddrqrlmkgqhxpg
3-4 l: llcqv
8-11 j: jfcnczqtfhgrcdxg
16-17 g: ggggvlggggggkggfqggg
14-16 v: vvvvdvvxvvvhkvvvvvvw
8-11 d: pdhdhddgdrdd
4-5 n: nnsnn
7-8 k: kwkkkkvg
2-4 k: lkbr
2-3 s: ssts
2-8 t: ttttptgttt
4-6 t: ztttghrtttt
8-11 h: hhghhhrhhhhhkgh
1-5 h: nwlpd
1-10 v: rgvvhvdzxzvnvc
7-8 p: zppnspqbpp
6-10 r: rxrrrrrgrr
7-9 c: hcbflccccbzcccrjgbpr
2-15 b: cbgtxwbmtjnszvbzzjkb
7-8 r: xrhrvrgsxrdf
13-17 g: mggxgqggrzgnggmgv
2-11 h: whqddhkhhqhh
9-10 c: ccccccqccc
1-8 h: mhhhjhhnh
16-18 s: sssssssssssssssssvs
2-4 z: txkz
10-11 n: jcwmzvknnnn
1-14 j: jljqfjjjjrlqrjd
15-17 b: bbbbbbbbbbbbbbzbgb
9-15 h: gfhcthccvhhchhq
16-17 f: gffvfqffffffffffffff
2-11 z: nzqzbnzkzlzm
1-9 b: vrfrkqbnctbbc
2-5 p: cpqrk
8-13 j: jjljpjjgtjbjfjj
3-4 j: fvjjqj
6-10 g: bnwlrgmggq
3-11 m: mzvmhmdmmmmmqgmmxm
2-8 b: lcbbbggpcbbzn
5-7 m: rtmmpmwm
4-6 l: hvlsnxlpmlvplqxng
1-4 n: nnnn
3-9 p: vnpmdjpvhw
2-8 r: bkrrwjpdg
16-20 h: hhhdhhhhhhwhhthhshqh
1-13 q: rqqqqqqqqqqqc
13-17 x: xlxxppdvmxxtxvbxsxx
5-7 p: ppppkpwp
3-5 d: dddkd
12-15 d: fddddnddddddddl
10-12 v: rvtmjfsncvpvvvv
4-5 m: mmlmm
1-3 t: jttqhdptjcjwnbjn
2-6 q: tqxqdqxdnltj
5-6 b: bjbwjn
3-8 n: nnnnnnndnnxn
9-11 p: hpcpbptztptppkpwp
15-16 n: nnnnnnnnpnnnnnkn
5-6 m: mmmxmmm
5-7 k: kkxkckk
9-11 t: dhtpttpqttt
11-15 v: vvvvvvwvwflvvvf
8-9 b: nrmgbbbbq
10-11 m: mmmmlmmqmmmmm
4-5 l: llrlll
8-14 v: jvvvvvvvvpvpvv
5-6 z: qzzzdj
7-10 j: jjpvfvjzckvh
1-2 c: chvfccfc
6-10 x: xxdxxxjdxtxxkxngxxpt
7-11 k: cchsjskkkpmkkkknk
3-4 r: mrrh
3-6 w: wkcpwsgwww
15-17 b: dbgxdbbkbrbzbvqpgdbh
4-5 l: llllll
8-11 g: gggpggvgggg
6-9 c: cpckccxcccjq
9-10 c: tcdchccpgz
1-8 t: stttvtttttttvtss
2-10 w: wmwnwwwwww
7-12 k: vknjkpkmzkrkkvqxkcn
11-13 m: mmmmmmmmmmqmdm
2-3 c: wczqmccc
3-7 w: vwpswwnww
5-9 w: ccwncstdz
2-5 d: fdddm
8-14 b: bqbbtctszzbbxrbb
16-17 n: qbknnnnnnnnnnnnnw
1-6 h: hhhhhhhh
1-5 t: vtbkvkxht
6-7 d: gdhdddddd
12-16 j: jcbbjwxbdktgzjzkjkx
7-13 r: nrrlrrxrfvrvgrrrgrr
11-17 x: xxxxhxqnxdkxccpfw
13-17 n: bxnnnnnnhdnnbnfnhn
1-9 k: gkkkkkkkpkkkkk
8-10 b: gbmpmzrbcg
11-14 g: gkgggvggggggrggg
3-9 d: ddddddqddd
4-5 j: tjjjjc
1-2 f: ffjpsr
6-11 d: dzmctkxrswz
5-16 d: qdsldjhdwldhddldz
4-8 q: qchgqqqrqqqq
1-5 w: mwwwwwclw
2-5 c: ccccswkcctl
1-2 s: nsnshgxjf
6-10 k: kkbqgkckjklklvknk
15-18 d: ddfddddrddddddjdddd
2-7 m: mwmmqmm
6-8 q: vqqmlqqqvqctqgqs
7-8 d: gddddzdddd
3-10 m: lmxmdmsmmpm
5-13 s: qslvssmtvrhtrxz
7-8 s: hbcsschfsrvssksrh
2-6 q: qvgkxgwvnjg
1-4 r: rrrkrrr
3-11 w: qxwwhwwclwfvbzxlkdxm
3-4 g: tgcq
3-4 j: dpmt
11-13 g: gcgbggggggdghlgggh
17-18 s: bbzjzlldsszsxgftsm
2-14 g: xhgdtfvzgpltkgzhd
1-4 k: klnk
1-3 z: dzpz
4-12 q: fprhqjxkjlwtnfg
2-3 b: bqhkb
3-4 k: ckvmkgsp
12-16 h: hhhhhhhhhchhhhhs
11-12 b: bbbbbbbbtzbvx
2-3 n: vnnx
2-4 l: lkftllf
1-6 b: bbqbbzb
2-7 c: bkqclfcwfxwkvcltsqqd
8-10 m: mzfmmmjmkm
1-5 s: dmlsf
5-11 b: bbqzgcmcbbdvb
5-7 l: lllllll
9-10 x: xxxxxxxxbcx
8-9 p: wppppppqv
3-5 m: mmtmmm
4-6 h: hhhhhhh
4-5 r: nsvckbrrhv
1-6 g: gggggggggcggg
1-2 x: xlvxgp
3-5 j: bjdnh
3-4 t: tttlt
4-9 z: tzpkksgrzhkxv
3-9 r: wrcrgjdwrmr
8-9 k: kkkkkkknkp
3-4 j: jgjjj
10-17 n: qmccjhsvbczwdntmktjx
8-10 c: cccccccfcq
14-16 m: mmmmmmmmmmmlmjvpmm
4-10 c: bhqzjcwnqkcwkr
17-18 n: nndnsnnfnnnnnnnnnfnn
2-4 x: wxrf
3-5 b: jbbsbnsbbwgnvj
2-6 r: hrmbrr
18-19 l: llllllclllllllllllll
13-16 b: bbbbbbbbbbbbbbbb
11-13 s: qsssszssslssw
9-10 v: vvvvvvvvcdv
5-11 g: ggvwgrkskph
9-10 b: bbbvnbqbcjd
9-12 c: vhcckfrzczkcc
16-17 d: dddndlddmddddddjv
18-19 h: hhhhhhhghhhhhhhhhrw
6-18 r: rrvjrrrwmhrrrddrrrn
1-3 g: jwfqhggfgt
1-4 n: xnnqlnncxbcncj
4-5 r: vrvwt
7-10 m: nxsqvmmwnkrqm
14-15 k: kpkkkkkwkkkkkkkkkrk
14-16 f: ffffdfffvffsfffff
3-7 n: dlflwdjwhlsdrnljccvh
12-13 k: kzkkkkkkkgksckkk
3-15 f: fffnfnzfhwhfmxxfd
3-8 z: wbztbsvbvqgxz
2-8 z: mzzqzzzzzz
8-11 x: slxvxxbzlxxbxmqxmxm
2-3 f: rffs
7-14 m: hvjmszmxgnnhnmpmfk
2-12 z: zpzzzjzzzszf
1-4 g: gbmgwghxpdb
1-3 j: twjjjqjwxljl
16-17 c: cccccccccccckccmc
7-10 g: gnzgggggpg
10-11 c: ccccccccccc
9-11 l: lllllplldll
11-13 q: wvcnqxvvqxqqq
6-7 r: jrsbrrrfvrprrd
4-7 v: vvvvvvsvv
6-20 d: cddnqddddddkvjddpdbz
2-8 m: mmsmmswmm
5-6 s: szssjs
4-6 z: zzzzzz
2-12 q: rqrtpmtpdqwqlsmpn
16-17 r: rrrrrrrrrrrkrrrwxk
1-11 v: xhvjjvvpvjdvpks
7-15 m: mmmfmmmmmrmmmmmmb
2-4 d: dddd
9-10 m: kmmcmwcmmxmmsmnm
10-11 m: mmmmmmmmmmm
8-9 p: pspctpxpppppwbqppp
11-13 s: ssbsssrrsswsgsss
6-9 f: pfrtffftfrfqx
2-3 c: sfcbscsx
18-20 p: pppppppppppppppqpppv
4-5 x: wsxbd
12-15 s: ssssssssssssssss
8-13 b: qmxcggxzbvdzhflplcvx
2-4 p: ppppp
10-14 m: mdgkvkrrxldnsm
6-8 x: xxxxmwxxxx
4-6 f: fffvfff
11-12 r: rrbrdrznndrrpwr
2-9 k: dflbckgsl
4-7 x: xgxxxxg
3-5 c: wphmkfxx
3-4 c: pccg
8-9 n: xqnzbbtnnq
2-4 s: sshsnw
4-6 b: lbbbbdxf
4-10 c: mhzcvkcxcms
2-3 z: zzdfz
8-9 s: hswsszfbblsssmstjf
2-14 r: prlnmrcrfxnmprr
9-10 t: gtpmrftnft
13-14 p: dpppppptprpspp
16-20 v: vvvvvvvvvvvvvvvvvvvb
3-9 t: tlttzdkwnvjt
3-4 b: bbsr
1-3 k: kkkk
3-5 k: kkkcn
1-4 b: kbbbbbhbb
10-14 p: bcppxppptppptpnnrxpp
1-13 x: zjbrdxlvmczvszxpj
2-7 x: zrxkxxxxx
6-10 n: vnmnjnnnnnnnt
9-11 c: dhzhvsfpmtrbp
2-4 c: vvcq
8-11 q: mpjlqqzkpqwnqqqq
13-17 x: fswnrkwvxvzhdmqdx
16-18 l: llllllqlllllclllllll
4-10 d: swpcgghdqp
10-14 k: kkkkkjkkkkkkkq
1-5 j: jfscjjckj
10-12 t: pztttttltttpttpt
3-4 h: chkm
8-12 c: gclmcpccccclrrc
4-10 v: vmgvvvvvvvl
4-6 m: wmmmmjm
5-6 x: xbjvzml
12-14 z: dzpzztzzlhhztz
4-5 s: ssrms
2-6 k: klchqkkzkbkbrwdkkw
7-9 v: vvvvvvzvmvvvv
8-9 h: zhhhphhjw
1-6 b: zbdlcbsvztmndkbbt
4-5 k: kkkgc
17-18 v: vvzkvvvvvvvvvvvvvvv
2-7 v: vcsvgjv
11-12 k: kkkkkkzkkkrk
1-2 r: grnkkcjrldpm
2-4 h: pkhx
11-14 v: vxlvhvxfjhvvvvv
7-10 q: qpqqqqtqrc
3-11 r: blrrlvtcbcr
10-11 p: ppplpppzpppp
10-14 z: qgjlzzqwqppztzzzdz
5-10 k: khkrzkkrkkk
1-2 l: ljlx
3-9 f: fpfzvddpf
7-13 g: ggcndgjgvglggggfpg
4-11 f: pfjhffffffqffff
1-16 b: lxwhmbbsbkbfbjcn
3-7 h: hhhhhkhssh
13-14 v: hvvvvvvvvvvvvvv
8-9 n: nnnnnnnnnn
7-8 n: nnxnfznnhnnn
7-8 c: ccccccdnc
1-7 w: ckwxwcwcwjvrr
1-4 c: cccgc
13-17 q: qqqqqqqjqqqqbqqqcv
4-5 l: llbll
3-8 w: xqwhmrwvvw
3-4 h: hhpw
3-8 q: fqqqnhtk
2-3 b: bbsb
1-3 f: ffffkrg
13-14 n: nnnnpnnnnnnnbnn
11-18 w: wwwwfwwwtjwwfflwwvw
1-3 v: jjvkrvv
2-4 h: qhgzhhxhvbrzjplsb
4-5 p: vpxpppwppl
3-7 j: jjsjjjvj
8-11 h: hhhvhmhdhhhhh
2-7 k: mkdmksjvk
2-9 n: ndnnnnnnqn
8-9 n: nntrjlnmt
3-5 f: xfbffrfc
3-4 g: gggg
15-17 p: pgpwpppppppppprpphp
6-13 z: zzzzzqzzzzrzqzz
1-11 r: bbjrzpnwlkmrsjxqjnvq
2-11 m: spkvwdnqtmsmvgtlfm
6-12 c: cccccpcccccmcc
7-8 w: fwxwwwwwbwwbw
4-17 r: rrrfrrrrrrrrrrrrr
2-3 q: qqqq
8-18 m: zsdmdprmdvkgqmdmhmx
4-5 g: ggggg
1-5 l: xfllltl
7-12 r: srrrrrvrrrvxrrr
2-6 p: pmpppppp
1-18 f: xfgffffcfffffffxfkf
2-4 g: qggrgg
4-16 m: wmmmnmmmmmmmkmqm
11-12 t: thztttdszzttntpbd
5-8 g: ggggbgggggg
3-5 h: knhbvh
1-2 q: fnqhqpc
11-14 v: qvvvvkxvvvvvzvvq
3-4 r: krssrrrr
1-13 w: kwwwwwwwwkwdwwc
5-7 f: zfffvfffffffff
5-10 t: fqtdtxcpwtbh
12-13 n: nnnnbnnnnnnnkk
7-9 t: wqkzfgtbsptfvt
6-11 r: ztwqxrmrrzp
14-20 f: ffffnffljffffrfcffdx
14-16 j: jjjjjjjjjjjjjcjv
4-5 f: xvfzqglkftpffbf
2-5 f: qftgffldffvdktfjshzr
12-13 t: cmpvlskpfcrsv
2-4 b: bbbpmqbbbbblbqbf
2-3 q: lqqkhqbq
4-10 j: qljhjftjvdbjjbtj
8-15 g: bgggwlbcggftggrgtdvg
10-11 j: jjjjsjvjjjjj
4-6 w: wbtwwwqvhtsrhbhzwhqw
4-5 r: frrhrx
1-5 c: ccccc
13-15 d: ddrdddrdddddvmdqnddd
4-5 j: xxpqdrfgj
12-13 f: bfbffmqffffftfff
1-4 s: svgs
8-10 s: sssssssssq
3-9 p: ppppbpppnp
1-2 w: wwxx
2-3 c: tccc
6-11 b: tkbxbbblsbsqdbwzbb
11-12 x: gxmxhxwxmxxxxvfxgxc
17-18 z: zzzzzzzzzzzzzzzznz
7-8 q: zqcwdvgqx
6-9 f: zmvsndwfgm
9-17 c: cccccccclcfcccccxccc
6-9 r: rrrrrrrrcr
9-12 r: rfzrrcrrrdrxrrr
2-6 v: svrlwmvlqfsd
16-17 h: hhhhhhhhhhhhhhhhph
11-12 j: jjjjjjjjjjbj
4-8 n: vncnbdzt
6-7 d: vdddddm
3-4 z: zzzz
1-5 q: qqqqfqqq
9-14 f: bnffhgpvffffnfftf
1-3 x: lkltxxxxxxx
2-4 l: llll
4-6 l: qhtldhlzbll
2-4 r: rrtrbb
12-16 m: mmmmmmmpmnmpmrmmmmm
16-18 h: hhhhhhhhhhhhhhmhhhh
4-5 f: qtfvfffff
3-4 c: ckkc
4-5 m: tmmmmlblzppmbk
4-7 x: ldxpxfckxfnfhfxwzjkp
3-5 j: dcdjsjj
6-11 g: lggggvsgghbfjgg
1-2 b: dmnbb
6-8 b: kxbbzbbbbwb
1-6 z: zzzhzwqzz
11-12 g: qggpggggggbpgg
13-16 x: xtxcwxxxxdxxxhjtnh
4-7 g: fgwgngg
7-10 x: xxjlxvqxxj
11-12 z: zzzzzzlqnzqz
5-6 d: mmbnbrdswk
8-9 k: vqkkkkkkkk
4-12 f: ljfhfhwfrdvf
5-14 h: rhhhhvhhhhhhhhhhhh
1-7 m: wmkgmsm
13-19 n: nqsnnhxnnnzvrpgljnmn
5-13 x: xfcxhxxxxxxxnxcx
4-15 p: pppppzpppppppppr
3-4 c: cctq
17-18 h: hhhkchhthhvhhhfhnc
3-4 r: xfdl
4-7 v: vvvzvvw
2-16 g: ngggdggqtgghprggngg
11-13 s: ssqsssnshwksgssss
1-9 h: hhhhhhhhhhhhhhhhhhh
6-14 x: xxxxxsxftzxqxfxsxr
4-6 d: wmddtttdt
17-18 p: ppppppppppppppppnpx
5-7 b: fbbbbbbh
7-13 s: ssjshlxhhjssqpsshssh
5-7 f: fntqfffl
7-12 h: hsvsxhhdhhjhhhh
5-6 n: jnnnpm
3-4 c: cfcc
1-14 k: kjkzqgnjdkjkvkpf
11-17 k: kgkkmkkbkkgsktvxvk
16-18 r: rfrrrrlrrrdrrbzkrb
14-16 j: jjjjjjjjjjjjjvjg
13-14 d: zddddxdddddlml
11-15 x: xxxxxxxxxxtxxxxxxxx
10-11 n: nnmnnnnnnnsn
9-10 d: ddddddddldd
1-13 m: dnmmmmmmmvqwwwgmmpmv
4-6 t: hvttttxttmtfv
6-7 p: ppppppdpp
3-4 g: pggg
17-18 z: zzzzzzzzmzzzzzzzwlz
8-16 g: ngcsgggcmgmglqgg
6-7 f: ffcxlhffgfvgdf
1-6 r: vwrrrrkr
5-6 k: knkkkk
6-7 b: vwdzwbbjbblbm
5-13 b: qkbxdhbqqczhcbqs
4-7 s: tsnsslsv
3-4 s: ssss
15-17 c: ccccccvcccccccbcf
11-14 c: ccccccccccdcct
1-2 q: rrndznlqgptbndbmrm
9-16 x: xxxpxxxxgxxxxxxvxx
3-4 x: xxzdxx
5-7 n: zndmnnln
4-5 t: jtntkttv
4-5 h: hhhgh
8-10 d: zdvmdsbzdvnnjpb
1-5 w: lqwmwp
9-10 d: ddddlglmdd
2-6 n: nncsmnkngc
7-9 f: hffgfffff
7-9 b: hbgblhbbbbwg
14-15 j: jjjjjjjjjjjjjlcj
14-16 k: kkkkkkkkkkkkkkgk
16-19 g: hxxmzgmcsbgcdrxfzgg
3-4 t: ttrmtt
8-14 h: qttzhtnwsxwhknqfmsj
3-5 h: cwltjhth
9-13 q: qqqqqqqqhqqqqqqqq
5-14 v: lzmdvmwlvbvrmvcvj
2-4 v: lvvv
5-6 d: dhddjdd
3-4 s: sssssg
7-8 z: nkzzxzzz
10-11 c: sccccccccccc
9-16 f: fbcftfffvlfqbvfff
11-13 c: lvccmccmcscllvc
1-2 v: vvvm
2-10 p: hkpppmpnpwmm
3-5 r: rrtnc
13-14 b: bbbbbbbbbbbbvbb
3-4 b: bsfvv
2-3 r: rrwrlrrrrbrrrr
14-16 c: cccccccccxcccccc
4-10 m: mmmmmqmmmm
11-15 j: jjjjjjjjjjjjjjjj
6-12 v: vvvvvvvvvvvwv
6-12 q: bbqhbszqnqqqqqq
9-13 t: tsxttrbttgttt
17-19 c: cccccccccccccccccccc
4-8 h: hnkgrsbzhhcsbp
5-6 t: tttgttttttt
3-4 w: sqsblvplnqjhxwnvkgfj
4-5 k: ckkkc
3-4 c: clrjc
2-4 z: zzcw
4-7 p: bpvwpmp
4-6 q: vjckzxbh
1-4 d: dnxdgjdd
2-6 g: ggjgjgkg
8-9 r: rrrrrrrvr
1-6 b: bbbbzb
13-14 q: qcqqqqqqqcqqwbq
5-16 w: zfwcxmjcncwtmtbvbctv
3-5 b: bpblbb
1-12 n: rbnnmgbnhklfnhn
3-8 m: nwmmmmlmx
2-4 p: wgpppwwdpv
4-9 h: dhhhmnhhh
1-9 c: ccfppznjsbccvsf
4-9 h: hhhhhhkhhhhhhhhhh
1-4 c: vsclwzcmc
3-7 j: sjrwfcrp
2-10 h: wqljchhhxhf
3-9 d: dddkdzqddsddd
10-11 q: cdgtzbrsvqq
9-14 b: rbjrtbmcbnlvbf
8-11 k: gkdkkkkhkkqrkzkvzwb
1-6 n: nsnxnnnnnnn
1-4 m: mqdmmx
2-8 s: sksshssgsls
2-4 c: cccc
2-5 v: vvvvvvc
7-9 h: hhhhhhvfl
14-20 f: bffhfffffffqfffqffff
3-5 l: llwls
1-6 p: nppbvp
9-16 c: wrkntcwncptccgccsclv
4-6 d: dldrlmddg
7-12 p: ppppfppsppppppplpm
2-5 v: vwmxvdvvvvdvnv
19-20 h: hhhhhhhhhhhhhhhhhhph
15-17 d: ddtdddtdddddddddd
2-6 q: qcqcqqqvq
5-6 t: tttttt
3-4 f: frfp
5-11 s: xlsdhkskzkczcntn
13-16 n: nnnnnnnnnnnnntnn
2-7 n: nnnnnnl
1-4 v: vqvbdfv
9-10 k: kkwtkkkkkz
8-11 z: zzzzzzzzzzzz
11-16 k: kkkkkkkkkkkdkkkkkkjk
14-15 c: rbctgvcqwccjctccrblq
13-14 l: ktdlflllgmlllc
3-5 c: cchccc
8-12 g: ggqggggvggqc
5-6 w: wwwwwm
2-4 f: mlfd
4-17 k: tknkjgcbdskbqvtvkkk
5-10 m: nwqmgjmmmdqmm
14-18 q: rqqqqqqqqqqsqqqqqrqm
3-5 m: mmbmm
6-7 b: bbbsbbl
1-5 w: wmwbvltncjxjsfhgw
1-16 b: zbwbjtbbzzlbcdbb
1-4 b: bbbb
1-4 x: xfzxxxxx
11-16 m: mmmmmmmmmmmmmmmmm
5-9 x: cxtxmsnqvxqxxx
1-2 v: vwvh
10-15 h: zghhhwgrhhjhhhhh
13-14 h: hhhhhhhhhhhhhh
11-12 d: dddddddddfmhd
1-12 w: wqbwwpzswwwm
1-5 c: cbbgc
11-13 f: nmffbmffffmfwffxff
11-12 l: llllllhllllll
12-13 r: gcrrrrkhbdgdrr
1-5 h: hhhhrhhhhh
1-5 g: ggggl
6-11 h: hgzxnhhhnqhph
1-9 x: xjkvwjgnxlrfdxxqxfc
4-5 s: ppsns
7-8 l: llllllwl
11-12 z: xzzrzzzzzzvsz
2-4 q: tzqqjq
10-15 b: vbrqbbmqbsbhmpbb
1-3 m: mmmm
7-10 m: mmmmmmgmgrm
8-9 w: wwswnwwwgw
1-5 m: mrmmm
3-7 b: whbbbbwqzbbtnb
3-4 b: bbsbb
11-13 p: pppppppnpbtpc
1-8 x: xvxvjxxxfqxvxx
6-8 m: hpmmbvmmpsmkmgs
7-8 l: llllllsl
2-3 t: ttttkttt
11-12 c: ccccccccccbw
1-4 z: vzzszz
12-14 c: ccwccccvtckrcc
4-14 k: xxmkcmnjdgqczkhk
1-15 j: ljwjjttjrjjjnjp
10-12 z: zzhzzzzzzzzz
5-11 w: cwwwwwwwgwww
10-18 n: hktgnnnjlwbzndrbpnl
6-9 m: mmpmmdmjtsmr
7-13 b: bcbwfbbbbbbfcb
3-12 c: mnmftdxxfpmnpzqhcm
2-5 d: dddddd
12-13 b: bbbbbbbbbbbnb
10-14 g: gggggggggwgggg
18-19 w: wwwwwwwwwwwwwfwwwxxw
7-8 d: wddddjddhdzddr
8-14 z: hgzzjbznzszzzgzz
7-8 f: ffffffbf
3-4 v: vvvv
9-16 n: nnnnnnnnnnnnnnnnnnnn
5-6 r: rrrrkf
13-16 f: fffffffffffflfff
14-16 f: gppfjbvfwllpsljp
9-18 f: ffffffffffffdfffffff
5-7 x: xxxxxxk
13-14 l: llvslllwvlhsccnllc
12-19 g: dtvgcdwgcmfsggcpgpgr
1-8 l: lwnwlxzllp
1-7 w: wwgkkwn
4-6 t: cttmtthltpctnsww
11-13 h: hhhhhhhvhnwhhh
1-5 r: rtdrrvsrrtrrlrtf
9-10 l: llllllgldlll
6-8 z: zzglzkznpkzz
1-4 n: nnlwvnq
14-15 m: mmmmmmmmmmmdmrtmm
4-16 s: ssmnssshsstsssrssss
1-5 g: zncgdpghsgs
7-20 r: rrrrrmgrfrbmrrrrrrrp
3-4 s: slrp
6-7 b: bbbbbbbb
10-11 b: lvxbvbbzhbg
5-6 k: kxzkzfftkf
4-6 h: hcjhhhn
6-10 r: krrrrjrrbwrnrrz
12-17 s: sssssssssjsrtlssswss
10-12 m: mmmmvmmmmkqm
2-9 j: nhjdzqjczxqjnw
3-4 b: bbbb
2-3 c: tzjcb
1-3 t: kmxtshpnzcln
3-4 x: xxxx
1-5 m: sjzszsmmbj
2-8 n: vnjnnnnnsnnnn
14-20 g: ggggkkggggggggggggkg
9-15 k: kzxckdjkkkhkkjktfkk
6-9 w: wwwwswwwwwbwcdb
8-11 k: kkqkkkkjkhfssh
5-9 q: hqqkdwtqxqhqq
8-9 t: tmtttttth
7-8 x: pqrjqsvscbffbkhfxhm
3-5 q: qqfqj
2-4 j: rjkjk
4-7 p: pppdpgtg
7-8 m: mmmmmwnm
10-12 x: xqxrxxxxtxtxxxxxxlx
5-11 c: cvdzctckcgmkgcm
2-4 k: vknkm
6-12 j: qjjgcrsjfbjpplnpjhr
2-7 p: ppppdpppkps
2-3 b: zhdbgb
6-9 d: dddddsdds
4-5 r: rmrvcr
14-15 p: ppppppppppppppp
1-4 g: gbgcgdkfwqbgngcqj
4-6 k: vnmkxkkkdkkkvpkc
9-10 h: hhhnfghhqlh
2-10 b: bbdfmqbbfbf
4-7 r: rrrfrrrr
6-8 k: kjlckkkzkkk
6-7 s: ssljsnw
12-13 d: dndddhldddjhpdddn
4-9 n: wkntqnnftcnn
7-10 b: bbbbbbbbbzb
3-4 q: vhvq
4-5 f: fgffnf
16-18 t: ftjjptkttvltbrthtlk
5-7 p: bpmprswpgzwsrbl
11-16 m: tmnlmgcgcmmmpwsr
4-7 j: jrnjjxjjjj
15-18 g: ggggggglgggggwgggv
1-3 k: kkkk
14-18 r: rrrrrrrrrrrrrrrwrrrr
1-4 f: ffff
7-9 b: bbbbbbbbbbb
15-16 z: zzzzzzzzzzzzpzpzzz
2-6 m: smvmtf
12-15 x: xxkvxxgxxxxvxxx
5-9 g: gggghfggrgmwgn
7-9 r: rfrfrrrxhrrrfnrmr
1-14 v: vvvvvvvvvvvvvt
16-20 t: tttttttkttlzsttvtttm
12-13 r: rrrrprrrrrlrrrr
14-15 x: xxxxxwxxxxxcxqwfxxx
1-3 c: jchc
4-12 n: nhnvmrrkknntnnn
16-17 n: nnnnnnnnnnnnpnnzcng
3-4 b: vkcbcwxnxxbbfhb
5-6 k: kklqnkkd
3-6 d: ddrddc
3-11 b: bbbbdbgbbbbbbtbbb
3-12 d: dsvpnrwhdddddv
9-10 b: bbbbbbbbbbbb
12-15 f: ffffffnffpfdffpfff
8-17 j: jjmjgxhdgvzjxjctj
2-5 f: fflqb
7-9 j: jjjjjjjjjj
2-3 c: ccccb
6-8 k: kzkkbkkk
1-10 r: rrrrrrrrrvr
15-16 j: jjvjjjjjjjjsjjjgjjj
6-16 k: fkkkkdjkkbkkkkkjk
7-19 q: jcspsdqsxrjsmnwvfqq
1-3 s: sdsss
3-6 f: mbfhffn
10-15 b: bgbbfgbbzbbbrrb
6-7 k: dkkjkwkcpmvhlhn
5-7 h: chhhbhc
3-4 c: wwcccccxp
2-4 q: qxqcq
6-7 j: jkjjjjjj
16-17 d: dddddddddddddddgf
2-5 r: rfqprwlrtffzm
1-4 f: kflmqf
7-8 t: ttttttttf
7-8 s: sssmsbvkssvs
5-10 h: jjhhhnjhthnkhkh
7-15 b: bbbrdbbmbzcbbbg
13-16 q: qfqqqqqqtqqqqqqqqq
1-2 p: ptksbpp
6-7 d: ddddrddd
6-11 k: kkkkkkkkkkkk
5-7 q: qqtqqqqfq
1-3 l: kwfllxlr
1-3 q: qqqqnq
8-13 s: sssssssssqsss
1-13 l: lllllllllllllll
1-2 x: xqxqxxxxxxxxxxxf
4-7 r: rrsjrprjwhrrr
10-11 t: ttfttttsttt
1-4 j: jpjj
16-17 v: vvvvvvvwvvvvvvvvvvv
3-4 v: qfvvwldqxr
5-6 m: nnwfrm
5-10 l: llpnqlllkml
3-4 x: ssttpxmbk
6-11 r: rkprqdqdrrr
2-5 m: mhmqpmh
2-3 g: gzmg
4-5 f: sfjwffvff
7-14 x: xmxxcjxbxvqqsxxgx
1-3 f: tfmffff
6-14 b: bbbbbbbbbbbhbb
4-6 r: qpldrgdlrplrx
1-3 t: ttmt
12-15 f: snlfkxrfcfwmkwwl
1-3 p: fpppp
7-15 g: gpgzggfgzkgxnpg
3-6 n: qtmndnzdzhwdjktlvst
4-8 x: xmxsxxxxx
4-9 r: rrrrrrrrqr
2-5 l: lllcl
4-7 p: phkzpnwcnppt
7-10 l: rdwhlrlprlfpt
2-3 z: tzscz
9-10 l: llmllllllv
1-4 s: sssslsxsss
1-5 j: bjhsrjwqndvjxnqkwjnx
6-16 c: xqgjtdgkgcxccqcgcwcs
7-12 n: dnnznccjbnnxnnng
15-16 f: ffffffffpfffflfmff
8-14 k: xwfbckjkgzxdxmqq
6-7 n: nnnnnpq
5-7 k: kkhkqkkgkk
2-5 c: ccckcc
8-9 b: bbbbpbblbbb
12-13 m: mmmmmmmmmmmjmm
2-9 m: mmtrksqzmx
12-14 d: rddpdrzsfcvpzz
4-9 c: ccckcccczc
1-3 k: kkkkkkkkkkkk
1-2 q: qqbzqqhxtj
3-4 x: xmxx
3-4 r: rrxqrrrgrgr
7-11 b: hbbbbbrbbzq
4-5 w: wwlxw
2-4 w: wgwww
5-7 p: ssddpppbpzp
6-7 b: bbbbbbbbb
4-5 w: kwwdwjw
1-3 m: xmsmmm
4-5 l: fllzl
1-2 c: nccgs
2-6 p: psphpskgbnvj
13-14 g: ggggghggccgqfjgggg
6-8 f: gmjfrvff
16-18 x: xxxxfxxxgxwxxxxxxsx
10-19 s: njsrgsssscssssssssc
2-3 h: hswh
2-5 g: gggbv
4-9 z: zzlzrpctzxm
2-3 h: lhhlhctg
17-18 q: qqqqqqqqqqqqqqqqqq
11-13 j: jjjjsjdjnzglfjnjjjj
2-4 k: kklk
6-12 p: pfpppzpppzpbpg
3-5 s: sbsssss
4-6 r: wzsrffr
10-13 r: rrrnrkfrrcrtnrlh
16-18 m: mmtmrxmmmmmmmmmcmmm
9-11 b: bkbltdvbtwbbtsb'
]

{ #category : #data }
AOC2020Tests >> dataForDay03 [
^'.#.#....###..#.#..............#
#......#####..##.##.#.......#.#
.###.....#..#.#..#..#.#......#.
.........##.#.....#.#..........
........##....#.......#.#..#..#
#.#..####...#.....#.#.#...#....
#....#...#.........#.....#..#.#
.#..........#..#.............#.
...##..##..#...####.#.#.#.#....
.#...####............##....#...
..##.....#.#......#......#.#.#.
..##......#..##.....#.#.....#.#
..#...#....#.#.........##......
#..##..##..#..##....#....##.#.#
..###.#....#.#.#...#......#.#.#
....#...#...#.........#.....##.
.#..#.#..........#.##.....#.#..
.#...#...###..#..#..####.#...#.
##..............#..#.#...###..#
.#..#.#.#...#..#...#..#........
..#.#......#.#..##...#.#..#....
...#.#.....#.##..#...#..#......
...#...##....##..#....#..#...#.
#......##.#.......#...#..#.#...
.#..#......####...#............
...#..##.#...#....#.#.#.#......
....##...........##.#.#...##...
#.##.###........#..###.#..##...
....#......#....##...##.#......
#.............#...#.........#..
..##.......#.......#.#...#...#.
...#....####...#...#....#.###..
...##......#...###.#...#....#..
...#.............#...#.......#.
...#..#.##.##.#..#.##.#..#....#
..####.....#..#............#...
##....##..#.#.#.#..#..#.....#..
......##...##......#.#.........
#.#............#.#.#..#......#.
...#.#.#.....#..#..#.#..##.....
.#.#.............###..#....##..
....#.###..#..#.....#..#.##....
..#.#....#.......#.......##..#.
.#.##.#.#..#..##.........##....
...#...###.##....#####.......#.
......#.....##...##...#....#.#.
###.......##..#.....#......#.#.
...#..#..#....#.#.....##..#...#
..#....##.......#....#.........
#....##.........##......#.#..#.
#.....#.#.#..##..#.#.....##....
......#....#...#...#.###....##.
#...####...###.##..#.#.#..##...
......###....###..##......#..##
.#.####.###..#.....#...#..#...#
.###.#.....#..#.#..#.....##..##
...##...#.####....#......###...
...##.......#.#..#......#.#....
......##....#......#.........#.
............#....#............#
..#.#..........#......#..#.....
.#...#.#.#......#..##..#....##.
..##.#.#.#..#...###..#.#.##.#..
..#......#.........#.......#...
...#...##.#.##......#.....#....
..#.....#..##....#..##..#.#.##.
....##....#.#...#..##.##.##....
..#.............#...#......#...
.#.#.#.##..#.#..##...#.........
.##...........#..#.#........#..
.#..##.....#....#...#...#......
#.#.....##.#..#...######....#..
....#..#...##...#.........###..
..##.#...##..#......#.##..#...#
##..##...........#.......#.#...
.......##..##...###.##.......#.
.#.##...#.##...............#...
.......#.............#.......##
......#...........#...#..##....
.#..#..#....#..........#......#
...........#..#.....#....##....
###....#....##..#..##.....##...
#........#........#...#.##.##..
##.#.#........#..#.#..#.......#
.##.#.....#............#.......
.....#........#..##......##....
.#.####.#.##..................#
#...##.......#...#....#.#.##...
#.#.##...#.#......#.....#....#.
.........#....#...#....#.....#.
...#..#..#.#..#.##........##.#.
..#.##.#...#...#....#....##..#.
.#..#...####..........#.......#
....#...#...#...##.#.##......#.
.#....#...#.#..##..##.#.....#..
.....#....#......#.#####...###.
..#...##..#......#.#....#.....#
.##....##..###.#.....##.##.##..
#...#.#.........#....#....#....
...#.........#.##....##.#.#.#..
...#...#.#....#..#.#.......#.#.
#......#..#....##....#.........
...........#......#......###..#
#..#...#..##..#....#.....#.#.#.
#.#.....##..#..........###..#..
#...#.....#.......#..##...#....
...#....##.....#..##..#....#...
#...#.#......#..#...#........#.
.#....#...#...#.........##....#
..##...#.........#.......##..#.
......#.......#.....##....#..#.
.....##..#...#............#.#.#
...#....#.##..#...#.#....#.....
...#...........#.##....#..##.##
##......##....##...........#.#.
..##..##......#...#.##.##..#...
.#..##.#...##...#......###.##.#
###.#....##..#..#.##..##...##..
..#........##.#...#.......#....
.....##....##.#.###.....#....#.
#.##....#....##.....#..#.#.....
#.........#..##...##.......##..
.#....#......#.#...##..........
##..##.....##....###..#...#.#.#
..##.#.#..#......#.#....###..#.
.#.##.....##.......##.#.##..#..
..##...#........#.#.#.##.#..###
........#.......#...##....#.#..
...#..#...#.##..#...#.#.###.##.
..#.#....#..#...#..##.........#
#....#..##..##....#.........#..
.......#.......#....#....#.#...
...#.##...#...#..#....#.###.##.
##.##...#..........#....#......
#.##.#.....#..#............##.#
.##...#.#.#.##...........#..##.
.#...#....#.......##...##...#.#
.#......#..#...#...#....#.#....
...#..#..#...#..##..##.....#..#
.#.##..#.#...#..#.#...#...#...#
#.##..........#.##..#....#.....
##....#.#..........#..#....#...
..#..##.#.......#...#.##......#
....##......#......#.#.#.##....
###......#...##..#..........###
##.#.##.....###.#..#.#......#..
#.#.#........#..........#....#.
...#.#..#.......#......##.#....
......#.....#.#.#....###..#...#
.........#...#..#####..#.#..#..
..........#.#.#####.#..#.....#.
....#.......#.#....#.....##..#.
#...##.#..#.#........#.#..#..##
#......#..#.#.....##......#.##.
.##...#....#.##..#.....###..#..
#....#.#..##....##..#.#####....
.......##..........#......#....
......#.#...#............#.....
.......###.....##.#..#.#....#.#
...#...#..........#....##...##.
.#..#.#.#....#.#.....##..#.#..#
......#.#..#....#..#...#.......
##.#####............#.#.####.#.
#.....###.#.......##...###....#
......#.##..##.........#.#.....
.#.#......#..#.##......#......#
.#.#.#..#.#...##.....#..#.#..#.
.#.#....#......................
#.#..###...#...####.##.#....#.#
.....#............#....#..#.##.
#..#...#.#....#....#..#..#...#.
...#.......#..#.#....#.......#.
.#..#.#...#.#.####..#...#....##
....#..#..............####....#
.....#.#.###....#.#.#.#...#....
..####..#.#.##.##.##....#..#...
.#.#.#.###..#.##..............#
..#.#..#...#.....#.......#.##..
.#.#..#.....##...###.....#..#..
..#..#......#.##..#......##..#.
.....#.#.#..##..###.#..........
.##......#...#.##.......#..#..#
.......#...#.....###.##...##...
..##..#.#.......#..............
#.....#......#.#..#..#..#......
..###.......##...#.##....#.....
.....##...........##.....#...##
.#.#.####....###.#.......#...##
#.#..##.#.#.....#.#....#.......
.........#.#..#...............#
..##.#..#..#####.###.........#.
.#........#...#...#...#.##.#..#
.#.##..........#..##....#.#.#..
.##......#....#.#....##.#.#.#..
.......##.####..#..#.#..#.#...#
...#.....#..##..###.#..##...#..
#.......##..#####....#.......#.
#.#.##.................#...###.
................####...........
.#..#......#...###.............
......#.#.##.##.....#..........
.......#..#.#............##....
#........#..#....#......#.####.
...#.#....##..#..#.............
..#.#......#...#.#..#..........
###...###...........#......#...
#.###..###........###...#..###.
.#.....#...#.#...........##....
....#..##.....#..#......#......
#.###.#........#.#.##..........
#.#.#.#.#..#.#...#...##.#......
..###.......###..#.#.#.#.#.....
...#........#.......#.###..##..
.#........#...#.#........#..##.
#.......###..#....##.###...#..#
.##....###..##...........##...#
#...#..........#.....#..##..#..
#..##..#..##.#.........##......
..#.#..###..###.....#.......#..
#...#...........##.#.#.###.....
...#....#.....#.....#.##.#.##.#
...........##.......####...#..#
#.#...#..##..#.#..#..........#.
..#...#.##........#.#..........
.##.....#.#.#....#.#.......#.#.
.......#.##...#.##....#.#...#..
......#...##...###...#.....###.
##......#.##.####.##...##......
..#....#.#..###.#..##....#..#..
...##..###.....###.....#.......
...#.....#.#........#..#..##.#.
.....................#.....#.#.
.#...#...##.#..#..........#...#
#.....#..#....#..#.......####..
.##.......##......###.#..#...##
.#.##..#...#..........##.......
...##...........##..##......#..
#....##.##...#......##.#.##.##.
..##.##.#.#.#....#........#.#..
....#......#......##..##.#.#...
.............#.##...#..#...#...
.#..#...#.........#...........#
....#.....#..................#.
........##............#...#..##
.###.....##...#...#.##.....##..
...##.#.........##.#.#..#......
#...........##.#..#........#..#
....#....#..##.#..##..#..#..#.#
#..##..#............#...#.#.#..
#......#..##......#...##..#...#
....#.#..##.#.#...####...#.....
.##..#..##....#...#....#...##.#
##.....#.#........#....#.#.#...
......#.#...##....#.###.....#.#
..#..#............###.###.##.#.
#..#.##.##.##..#...#.#.##..#...
....#..#.#...#......#..###.....
.#........#...###.....#...#....
....##.##....#..#...#.#####.#.#
...#..#...#.#.....#....#...###.
..........####...##............
.....#....##...##......#..#...#
..#...#.####......#...#..#..###
.#.....#....#..#...###..#.#....
..#..#......#.#...#.....##....#
.....##....#....#...#.....##...
#............##.#....#.#.#..#..
#......#......#....#.#..##.#...
#.#......##.....#.#..##.#.#....
.#.###..#.#......##...........#
#.#.........##..#.#.##......#..
##....####...##...........#....
....###.#..##.#.#.##...##.....#
..###.......##.......#......#..
..#.###.##.#...................
...#.#...#..#..#..##.###...#.#.
#...#..#...#..#....#..#...#....
....#........#.#.#.##.##.#..#.#
...#....#.#...#..#....#.#.#....
..#...#..##.#....##...###...##.
#......#.....#.....#....####.#.
...##.#..#.#.....#..#..##.#....
.####.#..#...#.#......#......#.
..#.#....#..#..##.#......##....
....#...#.#..#...#...##........
##..#.#....#..#.........#..##..
...#.......#....#..##...###..##
#......##.#..#..#..#..###.#.###
.#..##.#...##...#.............#
###.........#...###.#.#..#....#
.#.....#..#........#.#.......#.
#..#.#.....#.........###..#....
#..##.....#.#....#.###.....#..#
....#..#.......##..#.#..##....#
##.##..#....#..#.#.###.........
..##....#........#..#..#.##.#.#
.#....#...##..#.#.....#..##..#.
#..#.......#......#...#...#.##.
...##.#......#.#..#......#.....
......#...#.##.#....#...#.##.#.
#.....#..#.#.#...##...#........
....#.#..#.#.....#....#.#..#...
....#.#...###............#.....
.#.#...##.......#....#.##...#.#
.....#.##......#.#..#...#....#.
.###....#...#........#.........
..#.....#..#.#.#..##...#..#....
...###..#....#.....#.........##
#....#....###...#.#............
.#..##.....#...........#.#..#..
..#.#.#.......##..#.#..........
.#...#...####.#...#####.....#.#
..#....##.....#..#...#.........
#.#......#.##.........#......##
..#.#...#.##..#....#....#.##...
#....#......##.#..#......#.#.#.
#.#.............##..#.#........
..#.###.......##.....##.#..##.#
.........#........#...#..#....#
.........##.#.#..#..#....#....#
##..#..#.#.....##.........#.#.#
..##.##..#.##..........##.#..#.
...#..#####.......#.........#..
'
]

{ #category : #data }
AOC2020Tests >> dataForDay04 [
^'eyr:2029 pid:157374862
byr:1991 ecl:amb hcl:#a97842 hgt:178cm

byr:1962 pid:547578491 eyr:2028 ecl:hzl hgt:65in iyr:2013 hcl:#623a2f

hgt:71in eyr:2037
ecl:#8e276e hcl:z iyr:2019
byr:2022 pid:157cm

hcl:#733820 hgt:175 eyr:2028 iyr:2011
pid:87786389
ecl:hzl byr:1980

hgt:163in hcl:z pid:8261494508 cid:136 ecl:grn eyr:1958
byr:2030 iyr:1991

iyr:2021
hcl:6708a3
ecl:zzz eyr:2034 byr:2010
hgt:189cm
pid:466438311

iyr:2012 pid:9720867166 byr:2006 eyr:2022 hgt:72cm ecl:utc hcl:#c0946f

ecl:#353bc9
iyr:2020 pid:874363951 cid:113
hcl:z eyr:2040 hgt:76in byr:1975

eyr:1971
byr:1955 pid:193cm hgt:189cm hcl:#ceb3a1 ecl:grn
iyr:2023

byr:2014
iyr:2026 eyr:1978 hcl:z cid:312 pid:8294818417
hgt:169in ecl:#82bb02

ecl:amb
byr:1936 hcl:#7d3b0c pid:429853734
cid:342 iyr:2010 eyr:2025 hgt:160cm

byr:2025 hgt:176in hcl:a490ac
ecl:#956d3f iyr:2027
eyr:2021 pid:9858101884

hgt:142 pid:175cm
eyr:1952 byr:2004 iyr:2007 ecl:#da035e hcl:#623a2f
cid:194

hgt:156cm
pid:349122810 hcl:#b6652a eyr:2026 byr:1948 ecl:lzr iyr:2020

byr:1997 ecl:blu
hcl:#888785 pid:381094641 iyr:2014 hgt:192cm eyr:2027

hcl:7b10a2 ecl:lzr byr:2022
eyr:2035
pid:#38b715 hgt:190in iyr:2029

pid:188cm byr:2014
cid:241 ecl:#dda9bd hcl:#8f6ebc
hgt:188cm iyr:2014 eyr:2029

hgt:76cm ecl:gmt hcl:z iyr:2024
pid:3283057785
byr:2019 eyr:2026

iyr:2010 pid:284327216 hgt:191cm
byr:1970
hcl:#18171d
ecl:grn
eyr:2023

byr:1929 eyr:2026 cid:194 ecl:oth hgt:156cm pid:224596482 hcl:#b6652a iyr:2013

eyr:2030 byr:1958 hgt:190cm
pid:162950579 iyr:2010
ecl:brn
cid:250 hcl:#fffffd

ecl:xry iyr:2025 pid:#0155c1
hcl:#341e13
eyr:2027 hgt:163cm byr:2025

hcl:#602927 pid:908859481 byr:1962 ecl:hzl
iyr:2021 eyr:2028 hgt:180cm

iyr:1966 eyr:1976 pid:#bbfe21 hcl:63454a cid:259
ecl:blu
byr:2024 hgt:69cm

ecl:#644daf
byr:2021 eyr:2040
hcl:bc83fe
iyr:1976 hgt:59in pid:60311335

iyr:2018
pid:121801570 hgt:182cm ecl:blu byr:1922 cid:265 eyr:2024 hcl:#888785

byr:1933
pid:232653422 ecl:gry hcl:#18171d
hgt:171cm eyr:2035 iyr:2011

ecl:oth iyr:2015 byr:1937
pid:828621370 hcl:#602927
eyr:2026
hgt:193cm

iyr:2010 ecl:grn eyr:2022
hcl:af37d1 pid:761632482 hgt:65in cid:93
byr:1993

hgt:169cm cid:121
iyr:2018
hcl:#6b5442
pid:059725560 ecl:oth
byr:1972 eyr:2028

eyr:2024 byr:2023 ecl:gry
iyr:2017
pid:778551716 cid:256 hcl:#733820 hgt:184cm

hcl:#ceb3a1 pid:613277258 byr:1941 hgt:67cm eyr:2029
ecl:hzl
iyr:2017

ecl:hzl iyr:2012 pid:498418959 eyr:2022
byr:1929 hgt:164cm hcl:#a97842 cid:226

hgt:157cm eyr:2029
byr:1922 iyr:2014 ecl:grn cid:233 hcl:#888785 pid:802870003

hgt:184cm
ecl:oth hcl:#888785 iyr:2010 byr:1929 eyr:2030
pid:063671905

hcl:#888785 hgt:144 eyr:1961
iyr:2005
byr:2027
cid:164 pid:41787324
ecl:utc

hcl:#7d3b0c
pid:570743051 byr:2022 eyr:1975
iyr:2018 ecl:utc hgt:188in

eyr:2028 pid:970460968
hgt:161cm
iyr:2017 ecl:amb
cid:318 byr:1967 hcl:#cfa07d

hgt:183cm eyr:2036 hcl:070713 iyr:1959
cid:242 byr:2011 pid:#0855a5 ecl:lzr

hcl:#ceb3a1 eyr:2023 iyr:2016
ecl:oth hgt:84
pid:156cm byr:1949

eyr:2025 ecl:brn hgt:172cm pid:487559063 iyr:2013
hcl:#efcc98
byr:1985

eyr:2023 hcl:#6b5442 byr:2021 hgt:75cm iyr:1943
pid:427375038 ecl:#70c167

ecl:hzl
eyr:2028 byr:1957 iyr:2010
hcl:#602927
hgt:151cm pid:755290924

cid:184 hgt:172cm
pid:7056500139 iyr:2016 byr:2016
hcl:e40e08 ecl:#d21247

ecl:oth
eyr:2025
iyr:2010 byr:1971 cid:128 pid:932834922
hcl:#602927
hgt:167cm

ecl:brn hgt:61in iyr:2016 hcl:#341e13
pid:918193693 byr:1972 eyr:2029 cid:56

byr:1956 iyr:2020 eyr:2030 hgt:72in
pid:179969841
ecl:blu

ecl:#09fd92 cid:209 hgt:69cm iyr:2014
eyr:2028 pid:#2ad9c0 hcl:#b6652a
byr:2012

ecl:lzr byr:1980 cid:104
iyr:1965 pid:57029893 hcl:z
eyr:2030 hgt:64cm

pid:496149551
hcl:#6b5442 hgt:181cm byr:1978 iyr:2017
eyr:2026
cid:291 ecl:hzl

iyr:2018 hcl:#ceb3a1
eyr:2021 cid:183 pid:612653062
ecl:oth
byr:1982

hgt:153cm pid:877597531 ecl:gry
iyr:2014 hcl:#866857 cid:333
byr:1953
eyr:2022

iyr:2015
ecl:brn
pid:823959694 byr:1998 hcl:#18171d
eyr:2025 hgt:174cm

iyr:2012 cid:93
ecl:oth pid:142618419 byr:1955 hgt:193cm eyr:1977 hcl:#602927

hcl:z ecl:dne iyr:1926 eyr:2026 pid:175cm hgt:150 byr:2023 cid:234

hgt:61cm iyr:1965 byr:1956
pid:224946350 cid:105
eyr:1951 hcl:#733820 ecl:amb

hcl:#866857
byr:1970 pid:447859408
eyr:2030
hgt:65in iyr:2011 ecl:grn

cid:184 eyr:1976 byr:2021 hgt:187cm
pid:858786336 ecl:#0d63e1 hcl:z

hgt:178cm iyr:1986 hcl:51ac0c ecl:dne eyr:2023 pid:180cm

hcl:#cfa07d pid:002093179
ecl:oth
byr:1983 hgt:159cm iyr:2016 eyr:2025

ecl:gry hcl:#c0946f
byr:2009 pid:#e00fc8
hgt:62in cid:150 iyr:2013 eyr:1957

byr:1942 ecl:oth eyr:2020 pid:765036664 hcl:#6b5442 iyr:2015 cid:155

ecl:hzl iyr:2014
hcl:#efcc98 hgt:179cm eyr:2028
byr:1921 pid:#666905

ecl:utc eyr:2040 hcl:669f5b pid:981368190
byr:2006 iyr:1949
hgt:179in

ecl:#062fcd eyr:2035 byr:1962 iyr:2026 hcl:z hgt:161cm pid:75591618

hcl:#b25ef5 pid:434943296
ecl:oth hgt:165cm
iyr:2013 eyr:2020
cid:78 byr:1924

iyr:2018 ecl:oth byr:1972 eyr:2028 pid:035313920
hgt:59in hcl:#fffffd

hgt:185cm
hcl:#6b5442
cid:102 iyr:2020 byr:2001
eyr:2028 pid:003365121 ecl:amb

pid:90937712 hcl:z hgt:173in byr:2012 ecl:blu iyr:2009 eyr:2039

pid:509460932 eyr:2026
hgt:71in iyr:2010 cid:138 byr:1929 ecl:grn

ecl:xry
hgt:119
pid:051834447 eyr:2033
iyr:2030 hcl:z byr:2030

pid:443984745 eyr:2026 ecl:oth
byr:1948 hcl:#a97842 hgt:168cm
iyr:2017

hcl:#602927 iyr:2020 cid:161 pid:069708283 hgt:178cm byr:1960
eyr:2022 ecl:hzl

iyr:2026 hcl:766b30 eyr:2032 byr:2030 pid:40361792 hgt:158in ecl:#b300dc

eyr:1998 pid:#5c21e4 iyr:2029 ecl:#bef182
byr:1944 hgt:166in
hcl:#b6652a cid:317

ecl:amb
eyr:2024
hcl:#a97842
pid:086765271 hgt:183cm iyr:2018 cid:314 byr:2001

hgt:163in pid:491612094 iyr:2028
cid:82 ecl:#8a052d
hcl:#ceb3a1
eyr:2018

byr:1970 eyr:2039
hgt:174in hcl:#623a2f
iyr:2020 cid:154 ecl:grn pid:103138652

pid:73895324 eyr:2026 byr:1952 ecl:brn hcl:#733820 hgt:159in iyr:2015

hcl:#623a2f ecl:brn eyr:2026 hgt:185cm pid:791563822 iyr:2019 byr:1951

hcl:#fffffd
iyr:2014 hgt:83 cid:101 pid:724483094
eyr:1995 byr:2015 ecl:lzr

hcl:#ceb3a1
iyr:2013
eyr:2021 byr:1994 ecl:hzl
pid:037849486 hgt:60in

pid:63340670 iyr:1995 hcl:b54c2b hgt:71cm
cid:184 byr:2004 ecl:dne eyr:2026

hgt:169cm
ecl:brn byr:1947 iyr:2014 cid:224 hcl:#7374df

hcl:#623a2f
pid:471948403 ecl:gry
hgt:154cm
eyr:2023 iyr:2016 byr:1925

eyr:2024 hgt:180cm hcl:#efcc98 iyr:2020 ecl:gry byr:1961 pid:318184801

ecl:blu iyr:2012 eyr:2020 hgt:190cm
byr:1977
pid:331654452 hcl:#cfa07d

pid:812502106 byr:1938
eyr:2020 hgt:169cm ecl:oth hcl:#341e13 iyr:2011

cid:286 byr:1942 eyr:2034 hgt:116
ecl:utc
iyr:2023 hcl:#602927 pid:181cm

ecl:amb iyr:2011 hcl:#cfa07d eyr:2029 byr:1975
hgt:183cm pid:548900689

ecl:utc pid:182cm
hgt:60cm
eyr:1989 iyr:1993 hcl:z

iyr:1985 hgt:186 byr:2018
eyr:2001 pid:9257131167
hcl:261a65 ecl:lzr

hgt:152
byr:1922 pid:72992226
iyr:1968
ecl:dne eyr:2028 hcl:5c2950

ecl:grn
byr:1943 hgt:74in eyr:2022
pid:135491924
iyr:2011 hcl:#623a2f

iyr:2026 pid:7955389103
cid:311
ecl:#b81171 hcl:z eyr:1935 byr:2024

byr:1974 iyr:2010 hgt:165cm
ecl:amb cid:343 eyr:2023
pid:972786259 hcl:#6b5442

iyr:2020 byr:1936
ecl:gry hcl:#efcc98 hgt:170cm eyr:2021 pid:520354073

hgt:185cm hcl:#ceb3a1
pid:317012754 byr:1991
cid:199 iyr:2011
ecl:blu eyr:2028

ecl:#e4e01f byr:2008
cid:293 iyr:2013 hcl:z pid:#368f7a eyr:2036

eyr:2022 pid:424388475 iyr:2008 hcl:z hgt:61cm
ecl:zzz byr:1985

hcl:#18171d iyr:2014
cid:88
byr:1951 eyr:2021 pid:812441789 hgt:181cm ecl:blu

ecl:amb eyr:2029 hgt:70in pid:580245172
iyr:2010 byr:1927
hcl:#a97842
cid:284

hcl:#3b85ed
ecl:gry eyr:2029 pid:417534919 byr:1960
iyr:2010 hgt:71in

hcl:#c0946f
pid:824103775 hgt:157cm iyr:2018 ecl:brn eyr:2024 byr:1961

pid:673501373
eyr:2033
ecl:#06523f hcl:z byr:2030 iyr:1978 hgt:153cm

iyr:2019
hcl:#a97842 byr:1951 hgt:183cm eyr:2024 ecl:blu
pid:346079429

eyr:1937 pid:964649406
hgt:162
cid:66
ecl:#f89cc0
hcl:#866857 byr:2024

hgt:114 ecl:#e7ed3a
byr:2029 cid:190
eyr:2026 iyr:1986 hcl:z pid:185cm

hcl:#cfa07d hgt:192cm
pid:12494711 eyr:2028
iyr:2020
ecl:brn byr:2004

pid:710015269
byr:2011 eyr:2033 hgt:181cm
ecl:#fb2702

cid:259 pid:208799387
eyr:2025 hcl:#623a2f byr:1947 ecl:oth hgt:164cm iyr:2014

ecl:brn eyr:2025 pid:432178809 hcl:#341e13
cid:50
hgt:192cm iyr:2012
byr:1994

hgt:150in pid:4902585462 ecl:#7074ad cid:230 iyr:2019 eyr:1931 hcl:z byr:2007

ecl:gry
byr:1942
hcl:#602927 cid:178 iyr:2014 hgt:193cm pid:349100081 eyr:2030

byr:1923 hcl:#cfa07d eyr:2021 ecl:brn pid:591544598 hgt:157cm
iyr:2016

hcl:e15737
iyr:2017 byr:2030
eyr:1994 pid:470833249
hgt:181cm cid:70 ecl:grn

eyr:2030
hcl:#866857 pid:569423049 byr:1948
ecl:oth

eyr:2026
byr:2006
hcl:#ceb3a1
iyr:2010 pid:094156115 hgt:64cm ecl:oth

byr:2002 cid:215 ecl:hzl
hcl:#602927 iyr:2015 pid:53150410 hgt:168cm eyr:2028

iyr:2016 hcl:#7d3b0c hgt:162cm
byr:1937 eyr:2020 ecl:hzl pid:728906226

byr:1921
iyr:2018 hcl:#888785
eyr:2026 hgt:185cm pid:164432370 ecl:brn

ecl:gry iyr:2011
eyr:2026 hgt:190cm
hcl:#866857 pid:884570088 byr:1996

ecl:blu
cid:257
iyr:2016 byr:1989
eyr:2024 hgt:179cm hcl:#c0946f pid:418340261

pid:9367990743 hcl:z hgt:182in ecl:utc
byr:1988 eyr:2025

ecl:hzl hgt:157cm
iyr:2010 eyr:2027
hcl:#fffffd byr:1956

eyr:2024 pid:834302242 ecl:hzl
iyr:2015 cid:97 hgt:188cm hcl:#888785 byr:1927

ecl:brn eyr:2021 byr:1958
hcl:#a97842 hgt:170cm pid:256795932 iyr:2017

hcl:756c4a
pid:812879747
byr:2002
eyr:2027 ecl:blu iyr:1952 hgt:66cm

pid:#c5e14f
iyr:2026 byr:2028 hgt:162 hcl:87ba57
eyr:1952 ecl:lzr

hcl:#341e13 hgt:81 eyr:2021 iyr:2029 cid:262 ecl:amb pid:61006868
byr:2011

pid:#e58702 cid:145 hcl:#866857
ecl:grn iyr:2028 hgt:192in eyr:2025 byr:2017

iyr:2026 byr:1969
ecl:grn
hgt:70cm cid:140 hcl:e0f231 eyr:2027
pid:2832019

cid:112 eyr:2028 iyr:2018 hcl:#7d3b0c pid:868808117 byr:1985 ecl:blu

iyr:2017
pid:350399038
cid:72 hcl:#ceb3a1
ecl:gry
hgt:151cm byr:1946 eyr:2029

eyr:2026 hgt:174cm iyr:2010 pid:534641153 hcl:#733820 byr:1965

hgt:66cm
byr:2010 ecl:gmt eyr:2039
iyr:2024 hcl:z

pid:626085326
byr:1971 eyr:2024
hcl:#cfa07d hgt:170cm
ecl:hzl iyr:2019

hgt:185cm pid:995661846 ecl:hzl iyr:2016 byr:1963 hcl:#a97842 eyr:2023

ecl:grt iyr:1976 byr:2010
pid:170cm
cid:343 hcl:#7d3b0c hgt:171cm

pid:732695396
ecl:zzz hgt:151in byr:1955
eyr:2035 iyr:2026 hcl:z

hgt:187cm hcl:#341e13 iyr:2015 pid:556697270 eyr:2025 ecl:blu byr:1926

ecl:oth
pid:515980529
hgt:168cm eyr:2023
byr:1983 iyr:2012 hcl:#341e13

byr:2010
hgt:189cm iyr:2016
hcl:#8ff71e
eyr:2010
ecl:blu
pid:317940449

iyr:2013 hgt:157cm hcl:#a97842 pid:967988435
ecl:blu cid:214 eyr:2027 byr:1960

pid:2666548509 cid:208 hgt:72cm hcl:#7d3b0c eyr:2040 byr:2008
ecl:amb
iyr:1926

eyr:2039
pid:203432895 hgt:154cm byr:1949
iyr:2010
hcl:z cid:144 ecl:xry

pid:984689798 byr:2016 iyr:1999 ecl:utc
eyr:2037 hgt:68cm hcl:z

byr:1969 cid:230 hgt:72cm eyr:2032
ecl:gry pid:849701444
hcl:#c0946f
iyr:2012

eyr:2026
pid:588870142
hcl:#ae5619 hgt:173cm
cid:189
ecl:grn byr:1996 iyr:2013

byr:1973
hcl:#cfa07d ecl:blu
hgt:193cm eyr:2028 cid:115 pid:786380485 iyr:2011

hcl:#fffffd eyr:2028 hgt:155cm pid:499022582
ecl:blu byr:1977 iyr:2014
cid:212

ecl:#92bb4b
pid:815154669 byr:1923 eyr:2023
hgt:183cm iyr:1929 hcl:#ceb3a1

byr:1966 eyr:2021 iyr:2020 hcl:#6b5442 ecl:hzl
pid:3508035599
hgt:70in

ecl:amb
hcl:#18171d
byr:1927
hgt:177cm pid:555764540 iyr:2018 eyr:2025 cid:90

hgt:139 ecl:#878a7d byr:2006 cid:275 iyr:1980 hcl:60fca6 eyr:1952 pid:001439727

byr:1985
hgt:174cm ecl:gry
iyr:2018
cid:204 hcl:#733820
pid:141048398 eyr:2027

ecl:gmt hcl:#6b5442 hgt:158cm
iyr:2025
byr:2030 pid:966397365 eyr:2029

byr:1962 hgt:166cm pid:261989937 cid:320 eyr:2026
iyr:2015 hcl:#c0946f
ecl:hzl

pid:852283506 iyr:2018 eyr:2020 byr:1981 hcl:#733820
ecl:hzl
hgt:162cm

pid:3873488100 iyr:1982 ecl:grn
hgt:63cm eyr:1936
byr:2011 hcl:8d118a

iyr:1937
hcl:817646
byr:2026 eyr:2031 pid:#47591d hgt:183in
ecl:blu

eyr:2025 hgt:153cm iyr:2015 pid:498382864
cid:307
byr:1943
hcl:#f66fe1 ecl:oth

iyr:2017 hgt:66in byr:1948 hcl:#b6652a eyr:2025
pid:188366364
ecl:amb

ecl:lzr
pid:453174702 iyr:2028 eyr:2032 cid:228 byr:2011 hcl:z
hgt:172cm

hgt:186cm eyr:2030 cid:316 hcl:z byr:1994
iyr:2012 ecl:amb pid:993162839

hgt:160cm
ecl:grn pid:523473760 byr:1993
iyr:2016 eyr:2025 hcl:#602927 cid:261

iyr:2016 pid:520973843 ecl:gry
eyr:2023 cid:232
byr:1944 hgt:159cm hcl:#cfa07d

byr:1969 hcl:#1d37de hgt:184cm eyr:2027 pid:088048141
iyr:2016 cid:307 ecl:hzl

eyr:2040 iyr:2012 pid:723592140
hgt:61cm hcl:#18171d ecl:dne

eyr:2025
ecl:oth pid:4697392468
hgt:183cm iyr:2017 hcl:b07d71
byr:1996

ecl:amb eyr:2022 cid:143 pid:806594272 hgt:158cm byr:1977 iyr:2014
hcl:#866857

ecl:blu
eyr:2022 iyr:2018 byr:1983 hgt:167cm cid:321 hcl:#efcc98
pid:344179526

byr:1925 eyr:2021
hgt:193cm iyr:2020 ecl:grn
hcl:#888785

iyr:2018
cid:319 byr:1972 hgt:181cm hcl:#fffffd eyr:2023 pid:493780616

eyr:2021
hcl:#733820
ecl:#e91c71
iyr:2020 pid:451676066 hgt:166in
byr:1993

eyr:2026
hcl:#b6652a ecl:blu byr:1999 iyr:2020
hgt:163cm pid:955741810

iyr:2016 hgt:179cm hcl:#602927
pid:673271332 byr:1963 eyr:2027 ecl:amb

byr:1927
iyr:2015 hcl:#866857
ecl:oth
hgt:159cm
pid:992992996 eyr:2030

pid:283188332 hgt:168cm hcl:#6b5442
eyr:2027 byr:2028 ecl:hzl iyr:2030

byr:1944 pid:628012522 eyr:2020
hcl:#866857
iyr:2019 ecl:amb
hgt:168cm

cid:317 pid:333228098 hgt:158cm iyr:2014 byr:1958 eyr:2024 hcl:#a97842 ecl:oth

hcl:#733820
cid:314 ecl:oth byr:1938 eyr:2030 hgt:71in
pid:790938694 iyr:2014

iyr:2020 ecl:grt eyr:2018
hgt:155cm
pid:1034925815 hcl:#623a2f cid:304

ecl:brn hgt:158cm hcl:#38fe6c eyr:2030 byr:1926 pid:0860404500 iyr:1993 cid:348

byr:1998
hgt:185cm
ecl:brn eyr:2021 pid:567032567 hcl:#733820 cid:328 iyr:2017

pid:491430863 cid:146 hgt:181cm eyr:2026 iyr:2015 ecl:amb byr:1950 hcl:#c0946f

eyr:2033 cid:289
pid:396679011 ecl:oth byr:1988
hgt:156in
hcl:#cfa07d iyr:2029

ecl:grn iyr:2015
byr:1986 hcl:#a97842 hgt:62in
pid:403990108 eyr:2030

pid:42635067 cid:301
iyr:2027 hgt:173in
byr:2004 hcl:z
eyr:2034

byr:2020 hcl:#fffffd
hgt:180in eyr:2040 pid:304951921
iyr:2030 ecl:#1aaf20

iyr:2020 hcl:#888785 ecl:hzl hgt:181cm byr:1992 eyr:2021 pid:936006959

hgt:172in ecl:#fd71a7
hcl:787715 pid:363058480 byr:2020
iyr:2022
eyr:2034

iyr:2018 ecl:blu eyr:2029 hcl:#cfa07d hgt:155cm byr:1937 pid:851148031

byr:2014
cid:222 ecl:zzz hgt:67cm eyr:2040 pid:#8ab0e2 hcl:z iyr:2027

hgt:180cm hcl:#375883 eyr:2027 byr:1925 ecl:brn
iyr:2011
pid:158752719

byr:1935 ecl:oth eyr:2027 pid:041108579
hcl:#602927 iyr:2011 hgt:190cm

hcl:#a97842 pid:131728607 ecl:blu iyr:2014 hgt:176cm eyr:2020
byr:1921

pid:11754457
iyr:2018
hgt:65cm eyr:2038
ecl:dne hcl:z
cid:293
byr:1940

eyr:2023
iyr:2016
byr:1930
ecl:hzl
cid:212
hcl:#733820 hgt:59in
pid:319501919

cid:278
eyr:1967 hcl:#ceb3a1 pid:#9f5254 hgt:177in byr:1977 iyr:2030

hcl:#ceb3a1 byr:1998 hgt:72in cid:202 ecl:gry pid:463378493 iyr:2015
eyr:2030

hcl:#7d3b0c hgt:164cm ecl:hzl byr:1960 eyr:2023
iyr:2017

ecl:hzl hcl:#866857 byr:1986 iyr:2018 eyr:2027 hgt:176cm pid:928057092

pid:431113230 hgt:186cm eyr:2025
iyr:2018 ecl:amb byr:1973 hcl:#623a2f

hcl:#cfa07d hgt:179cm iyr:2017 pid:760075190 ecl:amb eyr:2030

hcl:#602927
iyr:2012
pid:571020910 ecl:#b6715d byr:1943 eyr:2028
hgt:161cm

hgt:176cm cid:121 pid:654127593 ecl:brn hcl:#160d38 iyr:2015
eyr:2021 byr:1997

eyr:2021 byr:1929
pid:192025713
hcl:#c0946f iyr:2012 ecl:oth hgt:179cm

eyr:2024 ecl:gry
hgt:158cm byr:1932 hcl:#ceb3a1
iyr:2010
pid:521188306

eyr:2028 ecl:brn
hcl:#efcc98
hgt:157cm
iyr:2012
pid:212547203 byr:1970

eyr:2029 pid:182693366 hcl:#623a2f hgt:130 byr:1972
cid:310
iyr:2010 ecl:amb

byr:1944 iyr:2013
ecl:brn cid:335
hgt:163cm
eyr:2025 hcl:#7d3b0c pid:405230824

hcl:#ceb3a1 iyr:2015 pid:572001387 byr:1962
ecl:amb hgt:151cm

byr:1928
eyr:2022
iyr:2018 ecl:blu
hcl:#602927 pid:767081131

byr:1948 hgt:180in pid:188cm
ecl:hzl
eyr:2013 hcl:e0b9f3 iyr:1975

hcl:#c0946f byr:1989
eyr:1980 hgt:67cm pid:538025041
iyr:2014 ecl:gry

eyr:2028 pid:958756919 hcl:#733820 byr:1945 cid:158 ecl:blu
hgt:168cm iyr:2018

cid:200 hcl:#fffffd
byr:2015 ecl:gry eyr:2031 hgt:59 pid:065027646
iyr:1967

byr:1999 ecl:hzl pid:813536928 iyr:2015 cid:296 hcl:#6b5442
eyr:2025 hgt:186cm

byr:2000 iyr:2012
hcl:#fffffd
cid:263 hgt:68in pid:105489529
ecl:amb eyr:2024

eyr:2026 hcl:#602927 hgt:181cm
byr:1982
pid:603871531 iyr:2018 ecl:blu

cid:302 pid:387895477 eyr:2027
hcl:#cfa07d hgt:191cm iyr:2015
ecl:hzl byr:1940

iyr:2018 cid:165
ecl:blu hgt:181cm byr:1994 eyr:2026 pid:077013268

eyr:2022 hgt:174in iyr:2010 byr:2023
hcl:#733820 ecl:oth
pid:311692961

ecl:#10f2a9 pid:964417986
eyr:2024 hcl:#0aeec7 byr:1965 iyr:1943 hgt:167cm

hcl:#341e13 iyr:2020
ecl:brn
hgt:188cm eyr:2021 byr:1952
pid:077471062

byr:1950 cid:110 hgt:160cm eyr:2026
hcl:#623a2f
iyr:2013
pid:972823574

pid:553704996 hgt:171cm
eyr:2028 iyr:2017
hcl:#18171d byr:1954 ecl:blu

hgt:180cm ecl:brn eyr:2029 pid:707999496 hcl:#cfa07d byr:1960

pid:9325738036 iyr:1996 hgt:152in byr:2004 cid:292 hcl:14a56f
eyr:2031
ecl:#dbd99d

byr:1957
eyr:2021 pid:557648216 ecl:amb hcl:#7d3b0c hgt:186cm
iyr:2020

hcl:#602927 hgt:186cm pid:604175608
iyr:2013 eyr:2026 ecl:oth byr:1991 cid:65

ecl:gry
iyr:2012 hgt:154cm
pid:872898058 eyr:2030 hcl:#341e13 byr:1994

pid:228236326
iyr:2013 cid:347 byr:1942
eyr:2021 ecl:brn
hgt:165cm
hcl:#fffffd

pid:392777182 cid:189 hcl:#cfa07d eyr:2027 hgt:191cm ecl:blu byr:1978

hgt:158in iyr:2028
pid:5145408095 byr:2012 ecl:#94c57d hcl:z eyr:1996

byr:1949 eyr:2021
ecl:#5ffbeb iyr:1948 pid:42650064 hcl:z hgt:167cm

iyr:2013 ecl:xry cid:100
hgt:138 byr:2013
eyr:1944 hcl:92b68c

hgt:187cm
ecl:grn hcl:#602927
iyr:2010
eyr:2022 byr:1949 cid:280 pid:251802347

ecl:grn
cid:219
iyr:2018 hgt:165cm
pid:703878503 eyr:2024 hcl:#b6652a
byr:2002

hcl:#18171d cid:341 ecl:amb byr:1941 eyr:2021 iyr:1990 pid:865132177 hgt:153cm

byr:2008 pid:861480549
cid:97 eyr:2028 hcl:#efcc98
iyr:2015
hgt:191cm ecl:#232b23

hcl:#cfa07d
eyr:2030 iyr:2013 cid:304
ecl:gry pid:199056608 hgt:192cm
byr:1926

pid:355135528 hgt:153cm byr:1998 iyr:2019 eyr:2027
ecl:amb hcl:#18171d

eyr:2028 hcl:8eed9c ecl:grn
iyr:2010 byr:2005 hgt:107
pid:64892698

pid:601671623 hgt:153cm iyr:2011 hcl:#b6652a byr:1975 ecl:grn eyr:2029

ecl:grn hcl:#18171d hgt:157cm
eyr:2023 pid:507932715 byr:1920 iyr:2020

eyr:2022 byr:1933 hcl:#fffffd iyr:2016 hgt:181cm pid:826522507 ecl:blu

byr:2002 hcl:#866857 hgt:177cm pid:240202426
ecl:gry cid:127
eyr:2022
iyr:2014

byr:1971
iyr:2017
pid:733985576 hcl:#c58c6c hgt:178cm
ecl:blu
eyr:2023

ecl:blu iyr:2017 pid:558732458 hcl:#1b3ab5 eyr:2025 byr:1967 hgt:176cm

eyr:2025 ecl:gry iyr:2020 byr:1988
hcl:#733820
hgt:189cm cid:151 pid:934827751

ecl:gry eyr:1951
iyr:1932
pid:309366394 byr:1945 hcl:#623a2f hgt:179cm

pid:462345884 ecl:hzl
cid:206 eyr:2021 hcl:#733820
byr:1982 hgt:180cm iyr:2010

iyr:2020 hgt:155cm hcl:#341e13 pid:110467532 cid:92 ecl:hzl byr:1975 eyr:2028

hcl:#18171d iyr:2010
hgt:182cm byr:1930
eyr:2024
cid:226

byr:1956 hcl:fb0c6f pid:181cm eyr:2012 iyr:2020
ecl:#d38822
hgt:69cm

ecl:gry iyr:2018
hgt:169cm byr:1981
pid:534824014 cid:287 eyr:2021 hcl:#c0946f

eyr:2039 hcl:#328e90 iyr:2015
hgt:170cm pid:#9fa2a4 byr:1999
ecl:#cd1fd7

hgt:190cm hcl:#733820
pid:302244363
ecl:brn
byr:1965 iyr:2013

iyr:2012
eyr:2021
pid:579705743
ecl:brn hgt:190in
byr:1954 hcl:#888785

eyr:2036 hgt:154cm
pid:800720865 byr:2023 ecl:oth iyr:2010 hcl:z

pid:#92f6a9 iyr:2028 eyr:1943
hgt:191cm ecl:hzl hcl:z byr:2018

hcl:#c0946f
pid:419930442 hgt:167cm
byr:1969
eyr:2020 ecl:brn

pid:137802946
eyr:2020 byr:1947 ecl:grn hgt:192cm iyr:2016 hcl:#888785

ecl:#f66cce eyr:1958 iyr:1954
pid:833131572
hcl:z
cid:212
hgt:109 byr:1924

hgt:179cm ecl:gry pid:065881341 byr:1985
hcl:#fffffd cid:204 eyr:2026

hgt:167cm
iyr:2017 pid:898571403 byr:1929
ecl:blu hcl:#d506d0 eyr:2028 cid:100

byr:1991 pid:2795214253 iyr:2011
cid:152 eyr:2028
hgt:170cm hcl:#a45065 ecl:lzr

hgt:188cm eyr:2030 iyr:2010
pid:297292695 byr:1955 hcl:#fffffd
ecl:blu

hgt:170cm eyr:2029 pid:913242036 byr:1993 cid:89 hcl:#888785
iyr:2010
ecl:blu

iyr:2028 eyr:2025 hgt:150in ecl:grn
byr:1995
pid:974802728
hcl:#cfa07d

eyr:2021 byr:1989
hcl:#18171d ecl:blu hgt:168cm
pid:626530259
iyr:2020

hcl:#6b5442 hgt:158cm pid:798732187 byr:1922 eyr:2020 iyr:2011 ecl:gry

hcl:#341e13 pid:092679330 byr:1997 ecl:oth hgt:159cm iyr:2010 eyr:2026

hgt:185cm
iyr:2020 byr:1947
pid:105846744 ecl:gry cid:134 eyr:2027

pid:252016128 hcl:9016ff cid:158 hgt:161 ecl:gry
byr:1952 eyr:1955 iyr:2018

iyr:2020 hgt:154in byr:1958
eyr:2029 ecl:#2feb89 pid:99780178

hcl:z
eyr:2001 ecl:gmt
byr:2022 hgt:73in iyr:2029
pid:388744230

hgt:186cm
byr:1939 pid:622948608 ecl:oth eyr:2030
hcl:#c0946f

cid:272
eyr:2025 byr:1979 ecl:brn hgt:180cm pid:456545466
hcl:#fffffd iyr:2012

pid:946657041 byr:1999
iyr:2014 hcl:#ceb3a1 hgt:150cm
ecl:grn

byr:1957 pid:177cm ecl:blu eyr:2020 hcl:#cfa07d
iyr:2010 hgt:183cm

pid:161cm eyr:2025 hcl:#b6652a
cid:213
ecl:xry
hgt:150cm
iyr:2024 byr:2012

hcl:ea1960
ecl:grn
pid:#7127b2 iyr:2012 eyr:2011 hgt:150

pid:178699291
hgt:66in eyr:2027
byr:1985 iyr:2014 ecl:amb

iyr:2017 ecl:blu
eyr:2027 hgt:191cm byr:1990 hcl:#b6652a pid:074411798

pid:528782860
hgt:181cm hcl:#c0946f byr:1965 iyr:2012 ecl:grn eyr:2020

pid:#ba10da hgt:176in byr:2006
ecl:grt
iyr:2030 eyr:1949 hcl:d3ca76

hgt:66cm ecl:#898478 hcl:#e9f7a5 eyr:2030 iyr:2022
byr:2025
pid:159cm

byr:1994 hcl:#ceb3a1
pid:028071950 eyr:2022 ecl:gmt hgt:151in iyr:2016

byr:2001 iyr:2011
ecl:brn
pid:487702556 hcl:#602927
hgt:167cm eyr:2026
'
]

{ #category : #data }
AOC2020Tests >> dataForDay05 [
^'FBFBBBFRLR
FBBFBBBLLR
FFFFFBBRRL
BBBFFFBRRL
BFFBFBFLRL
FBFFBFFLLR
FBFBBBBRLR
FBFBFBFRLL
BFFBFFBRLR
FBBFFFBLRR
FBFBBBFRRR
BFFBBFBRLR
BFFBFBFRRL
FFFFBBBLRL
FBBFBFFRLL
BBFBBFBRLR
BFFFFBBLLR
FBFFFFFRRR
BFBFFBFLRR
BBFBFFBLLL
BFBFFFFLLR
FBBFBBBRLL
BBBBFFFRRL
FFBBBFFRLR
FFFBFFFRRL
FFFBBBBLRL
BFBBFBFRRL
BFFBBFBLLL
FBFBBFFLRL
BFFBBBBLRL
FFBBBFFLRL
FFBFBFFRRL
BBBFBFBRLR
FBFBBBBRLL
FBBBFBBRRR
FBFBFBFLLL
BBFFFFFLLR
FBFFFBBLRR
FFBFFFBLRR
BBBFBFFRLR
FFFFFFBRRL
BFBBFFFRRR
FBFFBFBRRR
BFFFBBFLRL
BBFBFFFRRR
BBFFFBBLRL
FFBBFFFLLL
FFFFFBBRLR
BFBFFFFRRL
FFBBFBBLRR
BFBBFBBLLR
FFBBBBFRRL
BBBFFFFLRL
BFBFFBFLRL
BFFFFBBLRL
BBBFBBBRLL
BFBBFBBLRR
BFBFFBBRRL
BBFBFFFLLL
FFFFBFFRRL
FFFFBBBRRR
FBBFBBFLRL
FBFFBFBRLR
FBFFBBBLLL
FBFBBBFLLR
FBBFBFBRLL
BBBFBFFLLL
BBFFFFFLRL
FFBFBFBRLL
FBBBFFBLRL
FBFBFFBLRL
FFFBBFBRLR
FBFBBFBLLR
FBFFBBBRLL
BBFBBFBLLL
FBBBBFFRLL
FBBBBBBLRR
FFFFFBFLRR
BFFBFBBLRR
FBFFBFFLRR
BBFFFFBLRL
BBFFBFFLLR
FFFBBBBLRR
FBFBBBFRRL
FBBFFFBLRL
BBFBBFFRRL
FFBBBFBRLR
BBBFBFBRRR
FBFFBFFRRR
FFBFFBFRLR
BFBBFFBLLL
FFBBBFFRRL
FFFBFFFRLL
BBFFFBFLLR
BFFFFFBRLL
FFBFBBBRLL
FFFBFBFLLL
FBBFBBBLRR
BFBFBFBRLL
FFBBBBBLLL
FFBFFFBRRR
BBFBBFFRLL
BFFFFFFLRL
FBFFBFFRLR
BFFBBBFLRR
FFFBBFFRLR
FBFFFFBLLL
BBFFBBBRRR
FFBFBFBLLR
FBBFFBBLLR
BBFBBFBLLR
BBFBBFBLRL
BBBFFBFRRL
FBFFBBBLRL
BFBFBFFLLR
BFFFFFBRLR
FBFBFFBLLR
BFFFBFBRLL
FBFFFFBRRR
BFBBFBBRRL
FBFFFBBLRL
BFBBBBFLRL
BBBBFFBLRL
FFBFFBBLRL
FFFBFFBRLR
FBFBFFBRLR
FBFBFBBRRR
BFFBFBBLRL
FBBBFBBRLR
BFBBBFFLLL
BFBFBBBLLR
BBBFBBBRRR
FFBFFFFRLR
BBFFFBBRRR
BBBFBBFRRL
FFBFFBBLLL
BBFFBFFLRR
BBFFBFBRRL
BBFBBBFLRR
FBFFBFBLRL
BFBFFFFLLL
FFBBBFBRRR
BBBFBBBLLL
FBFBBFBLRL
BBBFFFBRLL
BFFFBBFRRL
BBBBFFFLLR
BBBFBFFRLL
FFBBFBFLRR
FBBFBFBRRR
FBBFBBFLRR
BBFFFBFRRL
FBFFFBBRLL
BBFFFFFRLR
FBBFBBFRRL
FBFFFBBLLL
BFBFBBFLLL
BFFBFFBRLL
FFFFBBBRLR
BBFBBBBRLR
BFBFFFBLRR
BFBFFFBRLL
FBFBBBBLLR
BFFFBFFRRR
FFBBBFFLLR
BFBFFFBLLL
FFBBFFBRLR
FBBFBBBRRL
BBFBFFBLRR
FBBFBBBRRR
FFFBBFBRRL
BFBFBFBLLR
BBFBFFBLRL
BBBFBFBRRL
BFFBFBFLLR
BFBFBBBLRR
FBFFFBFRLL
BFFBFFFRRL
FBFBFFFRRR
BFFBFFFRLL
FFBBFFBLLL
BBBBFFFRLR
BBBFFBFLLR
BFBFBFBRRL
BBFBBBBLLR
BFFBBFFRLR
FFFFBBBRRL
BFFFBBFRLR
FFBBFBBLLL
BBBFFFBLLR
BBFBBBFLLL
FFFFFBFLLR
BBBFBBFLRL
FFFFFBFLLL
BBFBFFFLLR
BFBBFBFLRL
BFBFBBFRRL
BBBFBFFRRL
BFFFBBFRLL
FFFFBFBLRL
BFBBBBBLRR
FFFBFFBLRL
FFFBBBBRLL
BBBFBFBLLR
BBBBFFBLLR
BFFFBBBLLR
BBFFFBBLLR
BBFFBBBLRR
FBBFBFBLLR
BBBFFFFRLL
FBBFBFBRRL
FFBFBFFRLR
BFFFFBFLLL
BBFBBBBLLL
FBFBBBBLRR
BBBBFFFRLL
BFBBFBBRRR
FFFFBBBLLL
BBFFBFBRLL
FBBFFBFLRL
FFBBBFFRLL
FFFBBBFRLR
FFBBFBFLRL
BBFBFBFLLR
BFFFFFBLRR
FBFBBBFRLL
FBFFFFFLLR
FBFBFFBLLL
BFFBFBFRLR
FFBFBFFLLL
FFFFFBBLLR
BBBBFFBRRR
FBFBFBFLLR
BBFFFBFRLR
BBFFBFBLRR
BFFBBFFLRR
BFFFFBFLLR
FBBFBFBLRL
BFFFFBFLRL
BBFFFFFLRR
BBBFFFFRRR
FFBBBFFLRR
BFFFBFBLRL
BBFBFBBLRR
BBFBFFBRLR
FFFBFBFLRR
FBFFFFFRLL
BBFBBBFRLR
BBFFBBFRRL
BFBFFBBRLR
FFBFFFBLLR
BFBFFFBRLR
BBBBFFBRLR
BFBFFBFLLR
BBFFBBFLLR
FBFFFFBLLR
FFFBBFBLRR
FFBBFFBRRR
FBBBFBFLRL
FBFBFBFLRR
BFFFBFBRRL
FBFFFFBRRL
FBFFFBBRLR
FBBFFBBRRL
FBBFBFFLRL
BFBFBBFRLL
FBBBBFFRLR
FFBFFFFRRL
BFBFBBBRRR
BFFBBBFRRR
BBFFFFFLLL
BFBBBBFLRR
FBBBBBFRRL
BBFBFBFRRL
BFFBFFFRLR
FBFFFBFRRR
FFBBBBBLLR
FBFFFBFRLR
BFBFBFBRLR
FFFBBBFRRR
FBBBFFBRLL
BBFBFBBLRL
FFFBFBBLLL
BFBFBFFLLL
FFFBFFFLLL
FBBBFBBRRL
FBFFFBFLRL
FBFFBFBRLL
BBFFBBFRLL
BFFFBFFRLL
FFBBFBFRRR
BBBFFBBRRL
BBFBFBBRLR
FFBBFFFLRR
FFBBBBFLLR
FFBFFBFLLR
FBBFBBFRLL
FBFBBFFLRR
BBBFFFFRRL
FFFFFBBLRR
BFBFBFFRLR
FFBBBBFRRR
FFBBFFFLLR
FFBBBBBLRR
FBBBBFBRRR
FBFFFBBRRR
BFFBFFBRRR
BFBFBBFLRR
FBFBBBBRRL
FBBBBFBRLR
BFFBBFBLLR
FBBBFBBLLL
FFBBBBBRLL
FBBBBBBRLL
FFFBFBBLLR
BFFFFFBRRL
BFFBFBBRRL
FBBBFFBLRR
FFFBFFFLRR
FFBBBBFRLR
BFFBFFFLLL
FBFFBFFRLL
BFBFBFFRLL
FBBFBBBRLR
FBFFBBFRLL
FFBFFFBRLR
BFBBFBFLRR
BFBBBBFRRL
FBFBFBBRLL
BFBBBFBLRL
FFBBFFBLRR
BBFFBBBRLR
FBBBFBBLRL
BBBBFBFLRL
BBBFBBFRRR
FFFBBFBLRL
BFBFFBBLLR
BBBFFFBLRL
BBFFFFBLRR
FFBBBBFLLL
FBFFFBFLLL
FFBBFBBRRL
BFFBBBBLRR
FBBFFBBRLR
BFBBFBFRLL
FFBBBBBLRL
FBFBFFFRLR
BFBBBFBRRR
BFBBBFBRLL
BBFBBBFRRR
BFFBBFBRRR
BBFFBBBRLL
FFBFFBBRLR
FFFFBBBRLL
FFBBBFBLRL
FFFBFBFRLL
BFBFBBFRRR
FBBFFFFRLL
BBBBFBFLLL
FBFBFFBRRR
BFFFBBBRRR
FFFBBFBLLL
BBBFBBBRRL
FBFFBFBLLR
FBBBBBFRLL
FBBFBFFLLL
BFBFFFBRRR
FBFBFBBLRL
FBFBBBBLLL
FFBFFFBRLL
BFFFBFBRLR
BFBFBBBRLL
FFBFBBFLLL
BBBBFFFRRR
FFFBFBFRRR
FFBBFFFRLL
BFBBBBBLLR
FBBBBFFLRL
BFBFBBFLRL
BFFBBBFLRL
BBFFBFBRLR
BBBFFBFLLL
FBFFBFFRRL
FFFBBBBRLR
BBFBFFFLRR
FBBBBBBRLR
BBFFBBBLLL
BBFBBFFLLL
FBBFFBFRLR
FFFFBFBLRR
FFFBBFFRRR
FBFBFBFLRL
BBFFBBFRRR
FFFFBFBRRR
FFBFBBBLRR
FBFFFBBRRL
BFFBBFBRLL
FFBFBFFLRR
FFBBFBBLLR
FBBBBBBLLR
FFFBBBFLLL
FFBBFFBLRL
BBFFFBBRLR
FFFFBFFRLR
BBFBFFBLLR
FFFBFBBLRR
BBFFFFBRLR
FBFBFFFRRL
FBBBFBFLLL
FFFBBBFRLL
FFFBFBBRLL
FFBFFBBLLR
BFFFBBBLRR
FFFBBFBLLR
FFBFBBFLRL
BFFBFBFLLL
BFFFBBFLRR
FBFFFBBLLR
FBBFFBBLLL
FFBBFFFLRL
BBBFFBFLRL
FBBFFFFLLL
BFFBBFFLLR
BBBFFFFLLL
FBFFBBFRRR
BFBBBBBRRR
FBFFFFFLRL
FFBFFBBRRL
FBFBBFFRLL
FFBFBBFRLR
BBBFFBBLLL
FFFBBBFLRL
BBFFFBBRRL
BFFFFFBLLR
FBBBFFBLLR
BBFBBFFLRR
FBFBBFBLLL
BFBBFBFRLR
BFBBFFBRRL
BBFFFBBLRR
FBBFFBFLRR
FFFBFFBRRR
FBFBBBBLRL
BBFFBBBLLR
FFBFFFBLRL
FBBBFFFLRR
BBBBFFBRLL
BFFBBBFLLR
BFBBBBFRLL
BFFBFFBRRL
BFFFFBBRLR
FFBFFFBLLL
FBBFFBFRLL
BFFBBBBRLR
BFFBFBBLLL
BBBFFBFRLR
BBFBBFBRLL
FFFFBBFRRL
FFBFBFBLRR
BFFBBBBLLR
BFFFFBFRRL
FBBBBFBLRL
BBBFFBBLRR
FBBBBFBLLL
FFFBFBBLRL
FFBFBBFRRR
BFBBFFBRLR
BBFFBBFLRR
FBBBFBFRLR
FBBFBFBLLL
BFFFBBFRRR
BFFFFBFRLR
FFBFFBFRRR
FFFFBBFRLR
FBBFFFBLLL
FBFFBBFLRR
BFFFFFFRLL
BFBBBFFLRR
FBFFBFBLRR
FBFBBFFRRR
FFFBBBBRRL
BFFFBFFLLR
FBBBBFFLLR
BFFFFFFRRR
FFBFFFFLRR
FBBFFFFRRL
FBBFFFFRLR
BBFFBBBLRL
FBFFBBBRRR
BFFFBBBRRL
BFFFBBBLLL
BFFFFBBRLL
BFFFFFFLRR
FBFBFBFRLR
FFFBFFFRRR
FFFFBBFLLL
BBBFBFBLRR
BBBFBBFLRR
BBFBFBBLLL
FFFBBBFLRR
FBBFFFBRLL
BFFBFFFLRR
BFBFBBBRRL
BFFBBBBRRR
FBFFBBBLRR
BFFFBBFLLL
BBBFBFBLRL
BFFFBFBLLR
BBBFBFFLLR
FFBFFBBLRR
FBBFBFFLRR
BBBFFBFRRR
BFBBFFFLRL
FFBBBFBLLR
FBBBBFFRRR
BFBBBBBRLR
BBFFBFBLLR
BFFBFBBRLR
BFFBFFFLLR
BFFBBBBRRL
BBFBFBFLRL
BFFBBBFLLL
BBBFFBFLRR
FBFFFFFLRR
BFBFBFBRRR
BBBFFBFRLL
BFFFBBFLLR
BBBFBBFRLR
FFFFBBFLRR
FBBBFBFRRL
FFFBFFBRRL
FFBFFBBRRR
BFBBBBBLLL
FFBFFBFRLL
BFBFFFBLLR
BFFBBFBLRL
BBFBBFFLRL
FFFBFBFRRL
BFFBBBBRLL
FBFBFFBRRL
FFFFFBFRLR
FBBBBFBRLL
FFFFBFFLLL
FBFBFBBRLR
FBFFFFBRLR
BFBBFFBLRR
BFBBBFFRLL
BBFBBFFLLR
FBFBBBFLRR
FFFFBFFRLL
BFBBFFBRRR
BBBFFFFLLR
BBFFFBBLLL
BFFFFFFRRL
BFBBFFBRLL
FFBFFFBRRL
FBFBBFBRLL
BFBBBFBLRR
BBFBFBFLRR
BBBFBBFLLL
FBFBFFFLRR
BBBBFFBLRR
FFFBBFFLRR
BFFFBFBLLL
FFFFBFFLRL
FFBBFBBRLR
FFFBFBFRLR
BFFBFBFRLL
BBBFFFBLLL
BBFBBFBRRR
BFBFBBBLLL
BFFBFFBLLR
BFBBFBBLRL
BBFBFFBRLL
FBFBBFFLLR
BFFFFFBLLL
FBFFFFFRRL
FFFFFFBRRR
BBBFFFFRLR
FBFFFBFRRL
BFBFFBBRLL
BBFBFFBRRR
FFBFBBBLRL
FFFBFFBLRR
FFFBBBFRRL
BFFBBFBRRL
BFBFFFBLRL
FBBFFBBRLL
FFBBBBBRRL
FBBBBFBLRR
BBFBFBBRRL
FBBBFFBRLR
FFBBFBBRLL
FFFBBBFLLR
BFBBFFFLRR
FBBBFFFLRL
BFBFFFBRRL
FFFFBBBLRR
FFFBFFBRLL
BFBBFBBRLR
FFFFFBBLLL
BFBBBFFRLR
BFBFFFFLRR
BFBBFFFLLR
FFFFBFFLRR
FFBFBFBLLL
BFBFBBFRLR
FBFFFBFLLR
FFBBFFBLLR
FBFBBBBRRR
FBBBBBBLLL
FFBFBBBRRR
FBFFBBFRLR
BFFFBFFLRL
FFBFBFFRLL
FBFFFFBLRR
BFBFFFFRLR
FBBBBBBRRL
BFBFBFBLRR
FFBFBBFLLR
FFFBBFFLLL
FFFBBFFLLR
FBBBFBBLLR
BFBBBFBLLL
BFBFFBFRLL
BFBBFFFRRL
BFBBFFBLLR
FBBFFBFRRL
BBFBBBBRRR
FBBBFFBRRR
BFFBBBFRLR
BBFBBBBRRL
FBBBFBFLLR
BFBFFFFRLL
FBBFFFBLLR
BBBBFFFLRL
BFFBFBFLRR
FBFFBFBRRL
BFBBBFFLRL
BBFFBFFRLL
BFBFBBBLRL
BBFFFBFLRR
BBFBFFFRRL
BFFBFBBLLR
FFFFBFBRLR
FFBBBBFLRR
FBBBBBFLLL
BFBBFBFLLL
FBBBBFBLLR
FBFBFFFLLL
BBFFFBFLLL
BBFBBBBLRL
FFFFFBBLRL
FFBFBBBLLR
FFFBFFFLLR
BFBFBFBLRL
FFBFFBFLRL
FBFFBBFLRL
FFBFBBFRRL
BFFBFFBLRR
BFFBBFFRLL
FFBFBFBRRL
FBFBFBBLRR
FBFBFBBLLL
FFFFBBFRLL
FBBBFFFRLR
FBFBBFBRLR
FBFFBBFLLL
BBFBBBFRLL
FBBBBBFLLR
FBBFFBBRRR
BFFBBBFRRL
BBFFBFFRRR
FFBFBBBLLL
FBBBBFFLLL
BBBBFBFLLR
FBBFBFFRRL
BBFBFBFRLR
FFFFBFFRRR
BFBFBFBLLL
BBFBBBBLRR
BBFFBFBLLL
BFBFBFFLRL
FFBFFFFLLR
FFFBBFFRLL
BBBBFFBRRL
BBFBBFBRRL
BBBFBFFLRL
BFFFBBBRLR
FBFBBBFLRL
FFBBBFBLRR
BFBFFFFRRR
BBBFFFBLRR
FFBFFFFRLL
BFBFFBFRRR
BFBBBFFRRL
FFFFFBFRLL
BBBFFBBLLR
BBBFFFFLRR
BFFBBFFRRL
FFBFBFFLLR
FBBBBFBRRL
FBFBFBBRRL
BBFFFFBRLL
FFBFBBBRLR
FBFBBFFLLL
FFBBBBBRLR
BFBBBBBRRL
BBBFBFFRRR
FFFBBFBRLL
BFBBFFFLLL
FFFFBFBRLL
BBFFBBFLRL
FFFBFBBRRL
BBFBFBBRLL
BFBFBBBRLR
FFFFBBBLLR
BFBBBBBRLL
FBBFBFFRRR
FBFFFBFLRR
FBBBFFFLLL
FFBFBFBRLR
FFFBFFBLLL
FFBBFBFLLL
BFBBBFBLLR
FFFFBFBRRL
FFFBFFBLLR
BBFFBBFRLR
BFFFFFBRRR
BFBBFFFRLR
FFFFFBBRLL
BBBFFBBRLL
BFFBFBBRRR
BFBFBFFRRL
FBBFFFBRRL
FFFBBFFLRL
FBBFFBFLLL
FBBFFFFLLR
BBFBBFBLRR
BBBFBBBRLR
FFFFBFFLLR
BFFBBFFLRL
BBFBBBFRRL
BBFFFFFRRL
BFBFFBBLRR
FFBBFFFRRL
BBFBFBFRLL
BFFBFFFRRR
BBFBFFFRLR
BFFBFBBRLL
BFFFFBBRRR
BFBFFBFLLL
FFFFFBFLRL
FBBFBBBLRL
BFBBBFBRLR
BFFFFFFLLL
FFFBFFFRLR
BFBBBFFRRR
FBBFFBBLRL
BBFFFFBRRL
BFFFFBBRRL
BBBFFFBRRR
BFBBFBBRLL
FBBFFBFLLR
FFBBFBBRRR
BBFFBFBLRL
FFBFBFBRRR
BFBBFFBLRL
BFFBBFFLLL
FFFBBBBLLR
FFBFBBFRLL
FBBBFFBLLL
BFBFBFFLRR
BFBBFFFRLL
FFBFBBBRRL
FFBBFBFRRL
FBFBBFBRRL
BFFBBBBLLL
BFBFFBBRRR
BBFBBBFLRL
BFBFFBFRRL
BFFBFFBLLL
FFBFFBFRRL
BBBFFFBRLR
FBBFFFBRRR
FFFBFFFLRL
FFFFBFBLLL
BBBBFFBLLL
BBFFFFBLLL
BBBFBBBLRL
FBFBFBBLLR
BFBFFFFLRL
BFFFFFFRLR
FFFFFFBRLR
BFFFFFBLRL
BBBBFFFLRR
FBBFBFBRLR
BFBBBBFLLR
FBBBBBFLRL
FFBFFFFRRR
FBFFBBFLLR
BBBBFFFLLL
FBBFFFFLRR
BBFBBFFRRR
BFBBBBFRRR
FBBBFFBRRL
BBFFFFBLLR
BBFFFFFRRR
BBFBFFFLRL
BFFFBFFLRR
BBBFBFFLRR
FFFBBFFRRL
FFFBFBFLRL
BFBFFBBLLL
FFBBFBBLRL
FBFFFFBLRL
FFFFBBFLLR
BFFBBFBLRR
BFBBBFBRRL
BBFFFBFLRL
FFBBBBFRLL
BFFFBFBRRR
FBBFBFFRLR
FBFFFFFLLL
BBFFBFFRLR
FBBBBFFRRL
BFFFBBBRLL
BBBFFBBRLR
FBFFBBFRRL
BBFBBBFLLR
FFBFFBFLLL
FBBFFFBRLR
BBFBBBBRLL
FBFBBBFLLL
FBBBBFFLRR
FBBBFBFRLL
FFFBBFBRRR
BBFBFBFLLL
BFBBBBFRLR
BBFBFFFRLL
FBBFBFFLLR
FFBBBFBRLL
FBBBFBFRRR
FBFBFBFRRR
FBBBFFFLLR
BBFFFBFRLL
BBFFBBFLLL
FFFBFBFLLR
FFBBFBFLLR
FBBFBBBLLL
FBBFBBFRLR
BFFFFFFLLR
FBFBBFBLRR
BBFFBFFLRL
BFFFFBFRLL
FBBBBBBLRL
FFFFFBFRRR
FBFFBBBRLR
FBBFFFFLRL
BBFFBFFLLL
FFBBFFFRRR
FFFFBBFLRL
BBFBFBBLLR
FBFBFFBLRR
FBBBFFFRRL
BFBFFBFRLR
BFBFBFFRRR
FBBBFBBLRR
BBFFBFBRRR
FFFFFBBRRR
BBFBFBBRRR
BFBBFBBLLL
FFBFFBBRLL
FBFFBFFLLL
FFBBFBFRLR
BBBFBBFLLR
FBBFBFBLRR
FFFBBBBLLL
BBFFFFBRRR
FBFFBBBLLR
FBFBFBFRRL
BBBFFBBLRL
BBFBFFBRRL
FBBFFBFRRR
FBBBBBFRLR
BFFFFBFLRR
FBBFBBFLLL
BFFFBFFRRL
BBBFFBBRRR
BBBFBFBLLL
BFFFBFBLRR
FBBBFFFRLL
FBFFFFBRLL
FBBFFBBLRR
FFBFFBFLRR
FBBBFFFRRR
BFFBFBFRRR
BBFFBFFRRL
FFBFFFFLLL
BFFFBBBLRL
FBFBFFFRLL
FBFBFFBRLL
BBBFBBBLLR
FFBFBFFRRR
FBFBBFFRLR
BBBFBFBRLL
BFBBBFFLLR
BBFBFBFRRR
FBFBBFFRRL
FFBBBFFLLL
BBFFFBBRLL
FBBBFBFLRR
FBFFBFBLLL
FFBFBFBLRL
FFFBFBBRRR
FBBBBBFRRR
BFFFBFFLLL
FFBBBBBRRR
FFFFFBFRRL
FBBBFBBRLL
FBBFBBFLLR
FBBFFFFRRR
FFBBBFBRRL
BFFBFFFLRL
BFFFFBFRRR
BFFFFBBLLL
FBBBBBFLRR
BFFBBFFRRR
BFBFBBFLLR
FFBBBFFRRR
FFBBFFBRRL
BFBFFBBLRL
BFFBFFBLRL
FFBBBBFLRL
FFBBFFBRLL
FBFFBFFLRL
FFBBBFBLLL
BBFBBFFRLR
BBBFBBBLRR
FFFBBBBRRR
BFFFFBBLRR
FFBFFFFLRL
BFBBBBBLRL
BBBFBBFRLL
FBFFFFFRLR
BBFFFFFRLL
FBFBFFFLRL
FFFBFBBRLR
FBBFBBFRRR
FBFBBFBRRR
BBFFFBFRRR
FFFFBBFRRR
FFFFBFBLLR
BFBBFBFLLR
BBFFBBBRRL
FFBBFBFRLL
FBFBFFFLLR
BFFBBBFRLL
FBBBBBBRRR
FBFFBBBRRL
FFBFBBFLRR
BFFFBFFRLR
BFBBBBFLLL
FFBBFFFRLR
FFBFBFFLRL
'
]

{ #category : #data }
AOC2020Tests >> dataForDay06 [
	^ 'gsvdkufnoawjmhp
wvhusojpnikgfadb
vshnpfedgwajkou
aujodhskfvnpgw
okpdnwhsfvjguqa

juedvq
vqeduj
veqdju
eqduvj

cdajbuernxm
mnucjearxbd
axrmdejuncb
jrebucmdxna

kutplibdoqzfvhw
qcewmrkdvhl
qobdwvlkgxhpasyjn

psbjhnatxe
pnaxesjhbt
tpxhbnseaj

yskvjqacinfdrphwltxgzomueb
jwprnxzvkeofthuqbyimadgslc

hzwepdg
lwf
wy
lw
rw

sdgateubqmznhjk
xyphltd

dbhl
hdlb
dbhl
hbld

inkxywsbgjuvpztrecadqmhf
qkaxszcujwvmbhdietpgr
krupsdgibzecxwvhqatmj
qtpxerobhisgcumkwjvdaz

bgakcmh
gxasvzu

cjtrvhinaqsbpk
jvxtspaqbhkfnrc

nab
bex
qmkudf

uot
out
tuo
uto
out

sbtkzf
hbkfzs
szbkf
fuzksbx
jskrzbf

dkphfoybsagcrnq
oybunchapqrdks
bokpysdhqnarc

bchumknwairvlf
cvbuhwzirkalfy

bwnseiaoqyjf
josqanfbew
nealmqbfwojs
jqnbfaoesw

sowzuji
wojizu
wzojiu
jwozui
ujiwoz

kcopqbt
tpkudorbc
pmtwogjb

uxkfthszqdbelomwri
tlusezbomwfqrdxhki
rsdfkbteoqilzmxhuw
bwkqmdsxhrfulietoz
izkwomsdlbfxetqhru

kzhwyodlvpt
kvfhldwpo
lvhypokdw
opwjhvdkcl
kpahtdolvw

cldyjpuitah
upcthlijyda
icdauhpytj
haypidtucj
jidaptcyhuo

mi
ti
qjwiz
oudehsxyiv
bpirjl

stlyornuk
cxapqwie

kharunjiebzvoy
gvaihtklnqmcebf

t
lt
t

ohca
lznkumqfgyjsbeot
owxdivpr

dy
yo
xsy
yo
pyrvh

iaxp
afpikux

hpsfqrnevzxl
fnrsvexzhqup

cp
fpc
cp

nbuojxgqckrwzspehf
mhguoxsfkejwcq
kedqujsomfxhwcvg
ouqefsxchgjkw
qcjohwxfseugk

rybnlomq
fmxsngauo
embkon
nlmvob
bomhnv

gptixlduzjeqkorsamwnh
pgzwohfjkuvbtylmc

thcgo
vhrlxmo

kbfgmhpzoqysac
ockazbsmhpgqfy
kmcqfyzhapgsxb
qcfdlwyarzuskhmbg

surovlcihp
irvlpuhosc

rd
d
td
d

koasgulh
kroumtzl
yubkwolnpj

dqykvasneb
easknpbovyjd

wqvop
nwqvpo
wovfrqizh
onqpwv

uskotfndjeplixhycbqrmw
mbxoewypcfdhistn
ydtvpbfemcnsihoxw
ynwbtosmcipxhfde

urgvbqechawznsjltixody
swdbnevcatrflguhziyoqxj
sgiwelhanovrbjuzyqtdcx
vyenojuhxwzbtigsdqarkcl

jxcwblszo
khrwvnbdolgjufyz

n
r
d
r
bd

tolrypvdwmb
lwrmopdvybt
rdybwmvplto
vlwpyrbmotd
ybolwtvprmd

radvoplnq
lrqpondva
lpanovqrd
lpanvoqdr
dqorvalpn

fvxca
vacfx
fvcxa

jbeixdakgolpfhqyntw
purbsxvjfwhetlmcnz

jztfgbmnkadiehv
djhpntcizmkgvbfe
btegdfknizvmhjl
igbdeztjfkhmnv
iqvtgejanzfdbhmk

jpi
ijp
ijp

kydp
viykd
dgyqmftwx
vdye

sewpkrvh
ekorswnp

bplerysifmzvwoncjxqk
nsbeqowitcpjymxvl

nexbskamprd
xsmdbkaupner
dsbnekarctvmpx
nkapxcbsmrlde
ezfdhnakwrsmyxpb

olnuzvxcgpdtfb
tgzcfdbnxp

vjliksorxpmwecaznu
giuoxsvnzewljpmc

fuljpkt
cplftukj
lfptjku
futpjlk

tqcgihveyswu
ywvqecthgs
cqhwetvsyg
qvshwcegty
gyctwqsfvhe

uhezlyxwvpcidr
hvucplszbxywer

jchyntk
revwzsm
kdn

cotikdlpxauzb
uxzptoksqbdiw

nqvruwhtombs
tebfnykzmlgcj

ciwkhzbmgfqo
uwmzgbcoihqkfs
fkwmziohcgbq

shezgrvq
gprveokq

jvqcdiuyrnpgh
dyjqvhrpic
xjiklpfzmthrwdsyqv
pdyvochrunaqjgi

denpjgywacrk
jbypwarecukdgn
zacqyxdgejrmpwkfnh
uwldpkrgaenjcy

q
mq
q

d
c
d
d

cdazeitlrpxnfqs
nrqxelfocsihpz
cnkveyiujlbzfgrpxq
cqznxrfliedp

qicgkpjzlxonv
cijozlhkqxnp
pgkcnloyxzj
japmxlknszotc

bytg
mwetjayhgiup
gyt
ygt
tyg

zx
elxz
z
vncto

nryw
rywn

takqgijzforxpshm
ztmrxfqgsiphjaok

fsaoqe
wcavsldeytn
auoekhzsi
hgseja

whqyvldpintefaxgurjc
xluqrgsvnacykptefbdhmj

oylknhsgmpawziqte
znhmatkpolsw
pkvmtznhlwsoa
onzamhltkpsw

zs
zs
zs
sz

e
a

xmi
gahfrd
yt
jmy
nqy

zkbtfdjom
ot
uoqtr
eot

g
er
g
g

ncvwupezd
cnvdwzpeu
cuwnzvedp
cdnzevwpu

bkuwcsv
bqcsgwve
mbhcovjsw
qwrnbeycsv
lisvbwc

vlys
omvzl
ptlejv
xylv
vxol

mqgohwtz
rqomlcw

rgopxhkslqcjmzbatnd
phgzmojlstadqrxkbn

pcbziv
pivzbc
jilczbpv

gmrecszl
zgrecslm
melzcrgs
gezcrlsm
mcsezrlg

ceotvxaydplfiu
vbzcaxuokwd

gy
g

lj
neocbiqjt

foyawivmhs
fayowsmzrv
mksfowvzayg

sivthk
yh
lh
ybhq
hy

fk
ka
vka
qhjxrzmckpb
kf

s
s
s

iyth
tyhri
yrtaih
htyi
utifydhq

hwxd
xhwd
hxwdb

kfhsvbjdwxcnt
dbfjhsctkvw
sogzdhjqiwmlyuvf

v
nyx
v
i

ncimwelvbudtp
piwvudaer

aktpdrhm
dtapkhr
dhapktri
taprnhdko
krpdhta

fvpaxk
zgmrwja
ar

vxoisla
olisvxa
kioqvrlxjhsya
oixgalsv
savloix

ac
gr
c
tl
c

fndwqsruzagei
dwunqfaesgzri
bzarmfnqwuisgde

jr
rj
jr
jr

zrevhj
xigdmqatk
wjlpzvsy

qijznvobp
nzbojivdpc
vzipojnb

srbtecvpixam
hdvctplmfxuow

bf
bf
bf
bfex

g
g
g
g
mag

b
y
b

vmbwhdfiqteglnpkxucjoa
wmqdconxbuaetjlgphivkf
upadfnhkwtjioqcbvxelmg
gofjubptnmkelihwxacqvd

alev
evla
alve
avel
aelv

uceyogrhl
oqcafluvhewgr
ugcxlhorpez
nduzshrceglox
odmgbeucrplh

ugesfliovyzja
nlizsujfadgo
lfguaszotij
osznifulgadkj
xadguljioszf

kpgve
vqsfezungalxidb
gwteov
gpvcyjrmeh

apuonkxtc
xithys
hfvtsx

pgtzamyqeu
gtiuwpcqzvya
tpqauezyg

souvmglcqbekzi
miuzvksocgqbel
gzqkmsubevolci

ndvahciz
jaoyhepsbirw

bghijfkotcxwu
uaokxsfbleyhgqr
hucfokpwbxg
nbfuztgovhxk

zghianxtlq
qthdvingxalkz
wfqnixgteza

lhzcrodupwqsv
phsvrzcldoqwu
hogspqwcvukdz
hwzpucdsqvrol

txkqmsfbglhnoypaduiv
navlozmpthwsbkiqxdfu

gidnojlbtfpskuwavyxczr
irvsyznbtedxougfwc
sovxhcqdbwytzmugrinf

mcjnraketsgvqyxpbuwlhzdof
kqudanprgiejcftzlywhsoxmb
rcxmkdqfohjzgtsalbpunywe

o
cm
rc
m

tmkbedxgzsw
tdgmsxbzkernw
ktdbxzsemgw
gwkmestbdxz
xzdewgtmskb

evpdgzcu
gepcvzu
vegzpuc
vpuzgec
cvpgeuz

wfsadgtuizejmylxq
aspmuqigbxeljdtwfy

ygbtdp
tye
fryaitjcukhl
ytdm

jfm
m
m

cl
cl
lc

qbodnftrsygi
iztorbfskqdvng
onpsgqrdtif
mnrofcuqwdtils

mhavcgzlrtbo
jrldgavzqbcxoh

pshtdbifrvzqmklyae
tfajgrpkidzyhslebmvq

cuzbjepnvis
isjbenvyzlcup
nagieshzcpqmfuvbj
ezvpsjrnciub

ywgdsafzuxbrmhvqkljnoipc
hjcntvrzwdfbxksyiqolpumag
kwvpybmjeoualxcsqgidhfnrz

zubvkn
cuwfsnv

isknfdalujeg
hikagvpzx

szgfhjtxid
stdgjzxfih
xghsjfdzit
gfjixszhtd
fzjshdtixg

uibgxka
abigukx
xubakgi
gxabiuky
bkaxgui

tjzor
slaore
gxwnoifudmcqvpk
obhr
tyo

q
y
e
r
ifdcxzm

fvtqrjsblkhuoiey
gyfnizlqupvscobt
bouiftlcvqsy
qdvlyfiusgotb
qvbycwsifluto

ifmnxbcvpkylruh
nckrmfphluixvby
vbcmxyhurnpilfk
suiqbvyrxcphmfnlk
ynuxkrfvibclpmh

pmvdyexsoilatqfgk
lpidgatmqevkxyso
gkpsaoleymqxvtdi
gmvxeyplqdoasitk
vkpdylstquegaiomx

ymogxuswkce
vbxznpscg
xlcgs
xclbdsng

zovwtiy
zrjlciov
ksxefuvqdam

cwvsx
xeuwyhsfb

hxwgolksbrdmpifye
lwpyefxmiohdnbksgr
gzoehypbldxikmwtrfs
sdlwpeymxifrbghok
glmbhykiofdxpwervs

ndcphgqfuvsekaxozri
xofkqnbschdaveruizgp

ptkvdhjaw
skhtapidwjn
thunakpjwd
eaglphkdtjcfw

pnezvfgiouahmslkdxcrqb
fpiqsecxaukbvzgnorjhwdm

emcwblgxuvnkzrdsoyjf
rvsxeugkmwzfncojlb
nhbiclvskjrupgxzfeomw
gcxlbjozeiufwnskvrm
eonjkwbzfxgpruvcmsl

ntgia
ia
ai

scoernukhwtigpd
bogiserhpucnkt

eaipzg
gne
lughe

tbipylmnrague
tbargijepmhuynl
triyzgupnbmale
prtnumgaibley
peblaytmgnrui

rqlsepfhiv
fvelqphsri
ilfhvqerps
fheqplsvir
sfpvehirlq

jciwxfbhqkadgzloprnuvsty
qwouetsmhykavxfbjzrglc

fjmz
mjczf
unkzjm

gebyncxsphfokwm
gmchsnbwkpfyxeo
fybkhcesogxpwmn

ud
whjn

ihm
hmi

p
p
yp
sp

ytrwx
yrtxw

p
d

ieltygdukac
yiudeakg
kpegdaiyu
audykegi
aeqydwiguk

lb
ei

zjvctfndgiqbeu
abfwndutvecqigz
fznbdutevigcq
qtvzfnueibdcg

g
i
x
g
g

qhm
lq
nq
pqsb
lvq

qnxpslvajf
xuavcnst
nsyabxv

ocu
uco
acoux
cluo
coun

jtgzodebq
ojztqdgbe
oejrqzgtbda
tjzbqedgo
gzqtejobd

ubglorcsyvmxd
oentwfgulpqikdcbzhj

jwkmxdnyvbiz
qebnoyfz

bepdfi
ikepbof

cofgekndbatpruhqmwvsiy
bsqtrakeudopghvyfmcnw
qgusdwvabytmfkcnehorp
qfhruygwkvmbpaoestcdn
prmkbuvynseatdoqwfhcg

enczdvbkiyjgruqp
bdiqvwjurpycngzk
bnrcejupvqiwgzkyd
pqgybrcjzkudonvi

fygasxjwrb
ijsgafwyrbx
syjawbxgfr
wfbrgvsjyax

xtp
bfnzuadh
xlce

rxmeqcbv

fjtdihkrbyn
htfjyinkgdrb
fibgtkdryhnj
hkbnjrftidy
intbxjrkfdyh

nhkiqjocfgxmrvwetd
ghnfdjvqtxwermokci
xnrtfkhdwcmjvoeigq
mcvfjhwiqtnrekogdx
imhxgjwrodtcknqvef

sabwqu
yqamws

usei
xkvnyfi

rcewysztbiamhpgldj
kibrfndmgeazcsh
adrzgchmwjsbie

pnrwvx
lwjxnu
vwxinb
pfxybwng

wnvxgfdkubzrmip
kmjhoigltwbz

znlgbx
fla
dl
l
l

jgeqcikplduzxrwby
kwplxgcbndjqyizuer
ewrqujilgyxpdzcbk

guteykxsqrfwhz
mhiurkswtqbxz
sdlqxvowujrhkz

zrejn
nzrje
jnerz
rzjen

fvkouigderaqbjth
eqrvwjinfltzpcuag

stqcrpy
ctsqpyr
ptyqrsc
ymsqrcaptb

egftpqosiv
ecjdqlnmwouf
spxaqofre
epogyfqi

oxwgtshjqef
pbtgjfeqhnoxw
jfhewygoxtq

jwavgo
ogevbwdjai
ogvahjw
wrajvog
ogsjwarv

rpucvg
cgpr
htfelpc

hqrwapscubelovxntd
jisztpnbcahlfdoqmvexgk

pmadwutiejznofcgvsbqyxh
qvmzbaisgfcunwjexhpdktyo
xtvsdnqaucyehgzbjiopwmf

vjqih
himjwdv
hsojivb
jtrklivehyg
mvnaizoqpfxhj

j
j
j
j
j

dpnwmtvklc
ndjpkm
ndmpk
ndmpk
ndmpk

ucojsptiqymhewbxvrfdkngl
ebpjwuxrdqkmsochvfgliznt

esroiaqdbxnjhut
xibuqhmensdajo
feukjbahdxwqnsiocv

vkxzclpmtujngerawod
azdrgcenvjxptkuolmw
onrluajvcgewpdzkmtx
xamlobkrvzwpjgnucdte
tvenjdmlzpwugkoracx

ywpfhztklgjmoien
nyelduixgvwmojpzhtk
lehpigtmoknjyzw
gmhwzokylpnteji
tmypejhwgzlniko

fmd
jf
fj

l
v
ntobg

drmzvt
rxtsfuk

vxdlpjkrsz
dgxkprvzsl
dsklxpvzr
pdvxzlrsk

gwip
gakpw

kbcadn
bakcd

mhpstqcgvoalkwxinebryzujd
qwhirveoczyatgjdsmkpxnl
mejazlincwodtshxkrpgqyv
fsaizhnkcvwolgjpdqxtmrye

rxubznovy
yvudnrbz
zvunwcyrkb
ntzbryuav
ndvytuzrb

utvklrxypgbnimsdofwa
fyzliqswjmtpvdka

byctfzx
pxzf

g
ik
ykei

bcajzwogvetd
gedbcwtzvoaj
hcwogaxjbzvted
eoczjagtdwbv
atvdjbcozgew

wsclketugyaz
qvfbjcxtmilgow

amgirw
yf

iletugq
hnoxbfkaspt

qjdfcpvksmxzywahgn
wnzceyskgpoxdhlmravjqf
xjgvhcsqyfankpzmdw
jyncdxwsqkvphfamgz
dvznygwjkcmqsxahfp

fkuwiezpljbdayhsr
rphwbeujdzlfiasyk
erdhpafkzbwjlusiy
jwfhkrzdeabpliusy
wfipeujhylazbsrkd

fqmbwapvouelydgicj
uelvqwomtyfjgcpadi
qkpcsdeyjiwarovnglfum
ijvgqdauoefpcylwbm
ydmqpfewaovlicugj

sgbq
ltqambf
djbuvn
zmtbgy

egvifnsaztxqcrywumj
aqcxujnzvfwetrhgm
fxdmtkgawplobqjenv

bxuwpnl
ztdkau

ecylsbdv
cvzlsbeyd
yqcveblsd
beyvlqcsd
ebsvdycl

eb
xpnyter

cbhqyzresnpxfwm
cwksfvhxqperbimz
whqzpbcsjxafre

beodiasvj
jbisdoave
iedaovbsj
jxovacsiebd

prxsnyehgwifbzo
ozpbsxynfiwrge
ribozypewsxngf
nyoxspzbfihgewr
rxzewpbnimfoysg

shviadjcue
weduziolmcbngp
vqdieycu
cudeif
dicyuqke

nvcwhuo
sltchuwnq
unwhci

ekrisbvx
rsxiev
exnrvsi
srxevi
xhsvnrei

rs
rs
sr

fuzjmek
tihf

ptlzxreqfdchibogvysmku
pceyizvdkqxbhrtulsfmog
gvkrxfsbipqedlyzomhtncu
suyzgrobilxhmcfdtvkeqp

okfvjneqyicuthwsmpxl
wdojlsqknyhmptvicfe
nyfjthmpivqgsulwkboec

ufrpkliqjgwxeybmcztasovh
qvkpyghxblewsaitrmzuonjc
giptzywrejquxkoavslcmhb
peaywubjozmcgrihlqsvxktf
lehjpzguiksacobxywtmvrq

egryz
ergyz
yzegr
yfcgzre

j
j
j
p
j

bjt
tbj
tjb
tbj
jbt

cklp
lpck
lckp

fea
eaf

qgm
dz

yri
yi
zypdi

ekwjxhtmgiudpz
xepuhgwjizkdrmt
ezghmliwtxujdpk
wdhxpjizugkemtl

gyokbspj
kbgsopyj
pykhdsjbgio
opjykusbg
jygbsopakc

ixorlekwgnbcjm
lrjkwxgie
wgeikxjrlh
rlkjxipeqgw

ecgmdrykq
myrclqdgek
guqmzyceprkd
dygckwerqm
yrcgkiqempd

u
u

bcwnvl
fcvsib
hcnvb
cpgveoaby
ivbcn

n
n
n

macuqyp
fs

pbout
suota
cuotm
atmuo

nlravibecfj
eilcjafn
aeibjfl
jxfeilauo
jafesdnli

xfwroij
fxwijor
irxjofw
rfjwboxi

dj
dvj
dj
dj

mikhxcqensrodu
imcvkhewgljupsxonq
kceuqxltinhsom
kzqanoemcxhius
vmuoxineqpzhacbks

hklcsoaywpfrdntmu
xirbzckwjvpfygeno

o
to
o

zvirefunh
ezhirnvfu
runifzhev
ezivhnrfu

zfsoducbpai
cupdisobazf
aozbsucfdiypv
bcfazodiups

njfprukxamlg
kpfrjgynulxma
pijflgnuxkram
pkuxalrmjfgn
nkvrlmxustpfjga

dszgm
rsmu

iaw
aiw
wai
aiw
iwa

s
s
s
sl
s

eyavhnk
keov
qeiwfkcgvrpsld
kuvze

a
mh

ilqchdfsog
igscolmdzq

fnyhxmpct
lchdpamfu

vijz
vj

dhpxjrmyuefclvqgni
uicskweohgvfryxmdq
tqgdifymexbwckruvh

c
c
c

lthidumvycszw
cvpqjeuhlwrfyzg

keocuw
uckowe
oekwcu
cwukoe

c
c

lkxjv
jkvxl
vxklj
jkvxlwg
zkxvjly

sqlamxeuhpgwjbdcioy
bumyjxsiqweholpgcda
gecswjlqhadiuboxmpy
syahibgopexwlucdqjm

igebmv
tawqvezdsmpunk
rimocvgje
evmbhc

ykjisvfatux
jfaisyvktux
itksajfxuvy

fclkush
slcykdbgu
fskuchl

xjhulywagzeioq
oejlfsquhbriayxwg
jiexgylwzhuqao
wyxhqljagieou
hwladixguqejyo

sofcbhuwyqtid
icofdwsb
dfwovimbcs
cwibodnsxf

jqnestpyaczfmxhwrbuvldi
mxanrhbfcujvyzditwlo

ntfgivkyszmarc
qrajdhowuvpclbex

kliwy
ukwlryi
ilkyw

pmgltzsk
ljmipztvgow
zltmgup
umztglp
ftzmlpgk

twepi
teq

ohyd
mytjrwk
hfy
exyh
ye

rzsqhtlowavy
twvhzyrjsqaol

yzagcqrjeimwxokh
fmxtiagboleqcwdrhzk
opvemhasrguxkcqzwi

atcpeyosnrjbg
kcesobgua
fagsev

ca
ac

xahmtil
hximtla

hyutnjdrbsmofl
dswjfyothmblrnq

et
te
eqt
tuje

nbhpwzgtrcx
gqcxobhriznw
hwnbugrejxtczs
cujrbxfhnwzg
gcwzhrxndjb

qwrfxhlyzcptvmkdeauigob
zbchavlkmryxiptegwfouqd
cfhuiptgqkoalrewzmvbyxds
hudmwcgbfepyitovkaqzxrl

eysuozkm
ndgloqyv
ignhwrovy

iqufgnvxspdcjtylkbrozh
inuzqktrvcxyhbgfosljdp

qhfknsyeuirzagvcwd
yfcgqnxewlkrsuazhi

lj
jl
lj
lyj
jl

kpholfxewrdt
opdfhtlmkwex
hpwftoxderlk
ylxhwdofnztkpe
rwfpxlhtdkoe

ubml
yvohg
zeasf
plum
qhnjxg

cjgzwmdyuakvixlprhfe
kmplfuxywergchzjvani
xcvlzmewyujgirhpfka
fwhgrxkjcvpeuilzyam

eclsiqp
ivgspoe
scepi
pmiadtskyze

akmdfivwgct
yvgcwakhdimts
lcvgirakwudtp
aftnckwmidgv

zuqblv
blvzqu
uvbqlz
qbuzvl
bzqxvlmu

by
betlcdvry
yb
bxy
gybjx

waoqdxpkmfnyrhjebcuvzs
qprvfczedowxknhausmyjb
cufdqvknwrajzybospmxeh
qkjzybeadvncwhxumpfsro
nwfkjxumpabzodvqychsre

shdfctjrkwbvemoxluyzipnqag
sgbwpeuqcilxojfynmrdhvktaz
lhgkxfwuzbevojmrpnqydsacti
gflnzjasbuyimxqcvwrdpohetk
ynwedhbskjtvoucgapiqlzfxrm

wlmjxp
ylnxoajk
luxjidte
xjrvlcdeu

pv
vbpw
wvuap
kceavp
rdphvoitqf

dlxzwkhtmc
twzhlmkdc
tcylhkdwzm
zwmlkdcth
gdhikmctlwsz

hpekwtlufyragqvb
kbrwatlupqyfvh
ucbvwlhfqatpkry
hlakvyuqrfpwbt
rubvwpfqlatkhy

npxobl
ckuhnplvx

edkpjycofasulrthw
rpuhcdyxlftosewa

stuvhwaexykzdorbfpi
shjuwgpfqmtacvlbirkzd

frph
wo
h
zumtyngcj
pfse

zivsgurp
szirpvg
gikvsprz
zigpvsrk
nvpsgzir

rfimu
hmqrlfxpbgu
nrmoyftu
nmujfr
rfum

bidzwmearovjkgcl
ogdbirkzqmclejvaw
gealcqozmijkbrvdw
gzakwmdbejclrivo
eolwifvgmrbjdazkc

iurfyqgwk
ymkvqfpwrig
aqrfywikg
bfdryxikgnwoq
cjfgkryiuwq

jvb
x

qkxnvfuopdytrzjgbm
bmqkuyarjgtdpfzsnox
obwjxyeqtingzmdrfkplu
gamupstryfokbzqdxnj

ymanp
npfshjya
pundyklatc
ypfanh

garp
grpa
arpg
argp

inedmtpwrvub
vwibertnudmp
idurbepwtmnv

yczoaplwmxibqgsfn
wbiuxyqzpncvgmsl
gpoltrbisqfznwxcymj

a
a
a
a

cgjviyufped
pcuvygzkjid
ptvigyjdcku

u
i
tqa
j
ul

zitbfuer
uzfithernb
uftbzire
uitefbzr

jcwkroamnegxvqsh
kejhanqmvcrxwsog
gaqmkexjvcsnrowh

taegslmuyqcipz
asytxrgdpfbcqliwz
tpgoschavqjlkyzi

oc
oc
oc
co

mrfvjlykquz
fzmvuleykqt
vykmzlgquf
kqfzuvygetml

a
s

ionve
eailo
jiomexwh
beziqpdco
ihtoe

cfjvrqosnwyedaubmhgtlxzk
olxzjfwrcytkbgudasvqhnme
tuwfnckrzsvjgbxdmyhqlaeo
txnydgufbmjaqkrzlwhoevcs
bgakxqmfsdwyjvelntchzour

njvkobzs
bsjvkwn

qmnluxw
ovgtikpdbrya
nchfsjqez

khtdryej
hdrtv
qnaodtm

as
aus

omjaixvgklq
vgkaxjihdrlq
ycxkzatpusiljqgv

jtepylmrqbiwk
xerlpmynqtkfbjwi
timwpbkegljqry
lqijkebmgpwyrt
qrkljpbytemiw

q
xqint
dkqb

trjmdxpoeqcwf
tfedxqcprwom
kmftwxqporncde

fpcmndhr
dzepjngqikcfrh
nhfpcrd

c
c
c
y
c

t
t
ti

tgfspxdy
sytgpfxd

zov
voz
ovz

ic
ieuc

vhesndkizjgwcpobulam
szjymxwopckfqtgdib

jdfzgqsbrmnticl
fbcdgqtznmjri
doitrczjqfbgmn
otzbjfidmnrqcg

cb
bc
cb
cb

aspjvghyurx
vcarwsbh
laeshvzrb
hsrvia

kpxzdhasfmltouvrc
duvpkascromz
vmcskupzorad

pguayqbwm
gpyaqbwum
ywaqgpmbu

ypdlnjse
elskbyz
jesylo
lyse

zlokqmjiurpwgbn
xzvurhgmlkwqnibjpo

wpzenbojcykqxvt
wnyzlbjkeoqtvcpx
itkjzydbpvoxcewnq

gfuvenodsizwmh
hwfuvsntdg

gkibnpalc
inkcgpal
gnpzliakfc

ibektdpuhg
iwbgjke
iycnergfqkbo
egxadvlmbijk

l
yjg
l

ymuoc
oymcu
oymcu
youcm
ycomu

wifoqy
zksfrict
bdpvhuilgejn
acoi
mqi

qrcukhwvzdjilpto
hqrmwkupclvjtizo

gdizlfawobuk
dihqfswcgukzrbla
gmukawbdfizlo

zwdrpv
dzvpwr

ycidkpfrqjelha
pjahykfecdqrli
kfqlajhdepyirc
pkhaceijlqdfry

pwuxbqotey
okbphqutfx
xvsgodubtlpqijr
puoewaxtbmq

qtbaoex
xpoqa
agiweqtop
nozuadmjrq

huvqdaij
fkuvaijdhq

biewrdlzc
rjlcikbzmdwve
leucwfpoizndbxr

avgtnubqcpxrhwdoml
vrkqgyndcmohtupswa

dmjqfesnxyciz
hfzudcjxsmno
mfjhrcsxznd
lcmbjnxzfadrs

tvayrhpqskd
qrtkvhyus
epjsytzhvrqk
yzqohmvtgsrk
hvlysqtwirbk

ieyd
aipeyg

r
rg
rm
r

qcweajhfmlgyzpv
ouqdxmsphkbatenr

fba
kfba
baf

vxpblsyjnrmkai
vpyhagcwqbzxmik
rpbytexdijnfavkom

fpmytnk
cyaw

jhyimdg
mhyij
hmvyij
mihezcovyj
yhmciej

sqfaopkgze
kxsecfphozq
qsotezpfk

ewcvoaurmjhq
cuqvjwreaohm
ewvjmqacuorh
wauhojecqmvrs

lyieuqdjcb
vkpctdmywzsreubn
delchbujy
jbcyegdou
xduayceb

nidxswarcqtk
kciqdarnbewsxt
acqrdkntipxlsw
ikpawtcdsqnrx

gikrfhwltveap
yeplvatowncgxirf
griadtewmvblpf

htjkmzxlvbygcwqioe
jzwtymxvigbheolckq
cxmvjyklobhtwgqzie
teczbxvlmgojqiwkyh
oxvejlbtiqywhzgmkc

jkfapozdwcie
bmushwjgltrn

rpnbxkoij
exjdri
uirjegxsa

zawoncbymgsrhv
dvctxgeusr
cvizgyhlmrwsfp

shnyujedctwfq
yscahxndftreq

xrnysi
itcluvmd
niqwozjber

gjobshlayxvctnfq
ljcxaonvbstqfgyh
ybhxgntqcsvfaojl
rjoxblqavncusgheytf
sncqlvybxfjtghao

uozb
ldewrck
xbg
xhg
z

yubqaznf
imwhrgnkjls

msvgjrnkcloaup
csxjnkgrpiuoveamy
pknvrajmcudswgzo
tnupacsxrgkvmoji
bpnkfarqumsvhcojg

bzvyuenaihfdcgwk
puchyenmzgksrijoa
ugebciktnlzhay

cedfutpnsivjlobrkaxy
denscvpbmlkxaojrfh

vugjrq
jqgtuwcnrv
grvkuqj
gbmvqsyxjueplzirhf
avudnjqgr

vpidajtmgozxwuksh
ughiwmakpjszdtvox
wugipxzdvastkhmj
sxughjakmnwfpdivzt
wimvaupjhgxstkzd

mqsuwhdxpcozfr
rsdwhfpakzxjmo
eysprldfqzowmhx
fodhrtmswxyzp

vsmzfbjhwqxiugtlc
gcqdsfmpletnhbxr

uxbgkfjwesmlchr
feakldxqnpwcjgvrzbhs
hjosrixfmlcgbkew

dszv
zsvd
vsdz
zvds
sdzv

pdw
lxudjpiwz
advnkpqw
hswpdog

gslpira
neuzf

ifjt
tjif
jfit
jitf
ifktj

jrnzb
unkjshpe
njza

ydigxaqm
iaeokqgmyhr

bkxmngtdlyev
nmbuzoveixlprkys

zjloghmtu
ermvzn
qzdncfm
afczxmp

aptscynieqmfgjhbr
bmsirnafyepthgcqj

q
qlr
fq
qk

v
v

ucrmbsozjkfy
buscrmofkzy
uosmfkryzbc
sqirbfzmocuynk
mbucykofrzs

lrp
plz
lrp
lp
lp

yfzmpgcsw
prycgfm
rfcmgpy
scgmyqpf
flcyvpohmgu

g
g
g
e

lxoaibjch
wudyrfvkzn
gtpmkeyqd

zjhlwbtfuvick
wujtvblzchkif

ksdfpvqbtxaluneo
dqofprhnxamskujeb

hacwigyftqblx
xwlqahitbgcyf
ahyxlwgtqifbc

mb
m
mg
m

ecrasdtyljuqimhnwfb
qleiaydjcugrwn
jdyewaqnrcliu

g
lqfio
adhstybz

gryzuxenhlvopbtmfwqcas
yeqzalmogbncxpsfujwh
mflqzhoaupcseygnbwx
myswzuonfqlaxecbhpgj

uwvzati
uzcjvtai
savuizt
atiuzv

cozuin
abuizo
tiozua
wilfzeoqu
roictxuz

gndpkojqu
gunkpsjoa
rtmzjpgkovwxlnuc

lrj
rjl
mrjl

udlpevjgzrfawitqs
qgrtiujslfeovza
surivgtfqjleaz
ezavgjtlfrusiq

g
fx
mf
tx
iyqd

sljgmdztynvrqexhwfi
gvwdyerlqnxthmjifsz
qgmjlfwrxztynivdhse

zkvuir
kvruiz
vriukz
kriumzv
zruikv

zyqgnvda
kdygvqanz
zyagvqdnu
qnwdmlaxgzyfvo
dnzgyavq

o
s
q

cbroy
qiyocmjdt
uyoc

lkqj
kjql
jqlk
ljqk
'
]

{ #category : #tests }
AOC2020Tests >> testDay01a [
self assert: #(1721 979 366 299 675 1456) day01a equals: 514579.

self assert: self dataForDay01 day01a equals: 1014171.
]

{ #category : #tests }
AOC2020Tests >> testDay01b [
self assert: #(1721 979 366 299 675 1456) day01b equals: 241861950.

self assert: self dataForDay01 day01b equals: 46584630.
]

{ #category : #tests }
AOC2020Tests >> testDay02a [

self assert: '1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
' day02a equals: 2.
	self assert: self dataForDay02 day02a equals: 569.
]

{ #category : #tests }
AOC2020Tests >> testDay02b [

self assert: '1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
' day02b equals: 1.
	self assert: self dataForDay02 day02b equals: 346.
]

{ #category : #tests }
AOC2020Tests >> testDay03a [

self assert: '..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
' day03a equals: 7.
	self assert: self dataForDay03 day03a equals: 145.
]

{ #category : #tests }
AOC2020Tests >> testDay03b [

self assert: '..##.......
#...#...#..
.#....#..#.
..#.#...#.#
.#...##..#.
..#.##.....
.#.#.#....#
.#........#
#.##...#...
#...##....#
.#..#...#.#
' day03b equals: 336.
	self assert: self dataForDay03 day03b equals: 3424528800.
]

{ #category : #tests }
AOC2020Tests >> testDay04a [

self assert: ('ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in
' day04WithPassport: #simple ) equals: 2.
	self assert: (self dataForDay04 day04WithPassport: #simple)  equals: 245.
]

{ #category : #tests }
AOC2020Tests >> testDay04b [

self assert: ('ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in
' day04WithPassport: #full ) equals: 2.
	self assert: (self dataForDay04 day04WithPassport: #full)  equals: 133.
]

{ #category : #tests }
AOC2020Tests >> testDay05a [
	self
		assert:
			'FBFBBFFRLR
BFFFBBFRRR
FFFBBBFRRR
BBFFBBFRLL
' day05a
		equals: 820.
	self assert: self dataForDay05 day05a equals: 978
]

{ #category : #tests }
AOC2020Tests >> testDay05b [
	
	self assert: self dataForDay05 day05b equals: 727
]

{ #category : #tests }
AOC2020Tests >> testDay06a [
	self
		assert:
			'abc

a
b
c

ab
ac

a
a
a
a

b
' day06a
		equals: 11.
	self assert: self dataForDay06 day06a equals: 6335
]

{ #category : #tests }
AOC2020Tests >> testDay06b [
	self
		assert:
			'abc

a
b
c

ab
ac

a
a
a
a

b
' day06b
		equals: 6.
	self assert: self dataForDay06 day06b equals: 3392
]
